#!/usr/bin/env node
/* gen_param_names.mjs — emit src/dsp/param_names.h from the engine enum.
 *
 *   node tools/gen_param_names.mjs
 *
 * TAL writes a preset as one XML attribute per SYNTHPARAMETERS enum member,
 * lowercased (`<program filtertype="0.18" cutoff="0.72" .../>`). The off-device
 * factory generator resolves those attributes with `enumMap[k.toUpperCase()]`,
 * which it can do because it parses Params.h at build time. The on-device
 * importer needs the same mapping in C, where there is no enum-name reflection.
 *
 * So generate it, rather than hand-maintaining a second copy of a 100-entry
 * table that has to stay in lockstep with an enum in vendored code. A stale
 * hand-written table would not fail to compile — it would silently import every
 * parameter after the drift point into the wrong slot.
 *
 * Emits names in enum order, index 0..NUMPARAM-1, with holes as NULL.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..');
const ENUM = join(repo, 'src/dsp/Engine/Params.h');
const OUT  = join(repo, 'src/dsp/param_names.h');

/* Same enum parse as gen_factory_bank.mjs — deliberately duplicated rather than
 * shared, because the two generators must keep working if either is deleted. */
function parseEnum(src) {
  const body = src.slice(src.indexOf('enum SYNTHPARAMETERS'));
  const inner = body.slice(body.indexOf('{') + 1, body.indexOf('}'));
  const map = {};
  let idx = 0;
  for (let tok of inner.split(',')) {
    tok = tok.replace(/\/\/.*$/gm, '').trim();
    if (!tok) continue;
    const m = tok.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*(=\s*(\d+))?$/);
    if (!m) continue;
    if (m[3] !== undefined) idx = parseInt(m[3], 10);
    map[m[1]] = idx;
    idx++;
  }
  return map;
}

const enumMap = parseEnum(readFileSync(ENUM, 'utf8'));
const NUMPARAM = enumMap['NUMPARAM'];
if (!NUMPARAM) throw new Error('could not resolve NUMPARAM from Params.h');

/* index -> lowercased name, for every member below NUMPARAM. NUMPARAM itself
 * and any sentinel at or above it are not parameters. */
const byIndex = new Array(NUMPARAM).fill(null);
for (const [name, idx] of Object.entries(enumMap)) {
  if (name === 'NUMPARAM') continue;
  if (idx < 0 || idx >= NUMPARAM) continue;
  /* An enum with duplicate values would make the mapping ambiguous; take the
   * first and report, rather than silently preferring whichever came last. */
  if (byIndex[idx] !== null) {
    console.warn(`[gen] warning: index ${idx} is both ${byIndex[idx]} and ${name.toLowerCase()}; keeping the first`);
    continue;
  }
  byIndex[idx] = name.toLowerCase();
}

const filled = byIndex.filter((n) => n !== null).length;

let out = `/* param_names.h — GENERATED by tools/gen_param_names.mjs. DO NOT EDIT.
 *
 * Lowercased SYNTHPARAMETERS names in enum order, which is exactly the
 * attribute vocabulary TAL writes into a .noisemakerpreset <program> element.
 * Used by the importer to resolve an attribute name to its engine slot.
 *
 * ${filled} of ${NUMPARAM} slots named. Regenerate: node tools/gen_param_names.mjs
 */
#ifndef NM_PARAM_NAMES_H
#define NM_PARAM_NAMES_H

#define NM_PARAM_NAME_COUNT ${NUMPARAM}

static const char *const NM_PARAM_NAMES[NM_PARAM_NAME_COUNT] = {
`;

for (let i = 0; i < NUMPARAM; i++) {
  const n = byIndex[i];
  out += n === null ? `    NULL,\n` : `    "${n}",\n`;
}

out += `};

/* ---- Aliases -------------------------------------------------------------
 * TAL has shipped more than one attribute vocabulary. Measured over a
 * 442-preset corpus there are exactly two, splitting 321 / 121, and they
 * differ in two ways:
 *
 *   1. CASE. The 121-file vocabulary writes delayfactorR, envelopeOneShot,
 *      lfo1Phase and lfo2Phase. The lookup below is therefore
 *      case-insensitive -- an exact-match lookup silently drops those four
 *      real parameters from every one of those presets. (The off-device
 *      factory generator never hit this because it resolves via
 *      enumMap[k.toUpperCase()], which is case-insensitive by construction.)
 *
 *   2. One genuine RENAME: velocityfilter <-> velocitycutoff. They never
 *      co-occur, and both vocabularies carry velocityvolume and
 *      velocitycontour, so by elimination velocityfilter IS VELOCITYCUTOFF
 *      (the wrapper labels that param "Vel > Cutoff" -- same control).
 *
 * Attributes in neither table (midiclear / midilearn / midilock / unknown)
 * are GUI state with no engine slot and are safely ignored -- but the
 * importer counts them, so a THIRD vocabulary shows up as a number rather
 * than as silently missing sound. */
typedef struct { const char *name; int index; } nm_param_alias_t;

static const nm_param_alias_t NM_PARAM_ALIASES[] = {
    { "velocityfilter", ${enumMap['VELOCITYCUTOFF']} },   /* == velocitycutoff */
};
#define NM_PARAM_ALIAS_COUNT ((int)(sizeof(NM_PARAM_ALIASES) / sizeof(NM_PARAM_ALIASES[0])))

static inline int nm_ci_eq(const char *cand, const char *name, int len) {
    int j = 0;
    for (; j < len && cand[j]; j++) {
        char a = cand[j], b = name[j];
        if (b >= 'A' && b <= 'Z') b = (char)(b - 'A' + 'a');   /* cand is already lower */
        if (a != b) return 0;
    }
    return j == len && cand[j] == '\\0';
}

/* Attribute name -> engine index, or -1. Linear scan: called once per
 * attribute per preset against ~92 entries, which is noise next to the file
 * read itself. */
static inline int nm_param_index(const char *name, int len) {
    for (int i = 0; i < NM_PARAM_NAME_COUNT; i++) {
        const char *cand = NM_PARAM_NAMES[i];
        if (cand && nm_ci_eq(cand, name, len)) return i;
    }
    for (int i = 0; i < NM_PARAM_ALIAS_COUNT; i++) {
        if (nm_ci_eq(NM_PARAM_ALIASES[i].name, name, len))
            return NM_PARAM_ALIASES[i].index;
    }
    return -1;
}

#endif /* NM_PARAM_NAMES_H */
`;

writeFileSync(OUT, out);
console.log(`param_names.h: ${filled}/${NUMPARAM} parameter names emitted`);
