#!/usr/bin/env node
/*
 * gen_factory_bank.mjs — bake TAL Noisemaker's factory programs into a C
 * header the wrapper #includes.
 *
 * Reads the vendored plain-XML bank (tools/factory/tal_factory_bank.xml,
 * decoded from the vendor's ProgramChunk.h via decode_program_chunk.mjs; each
 * <program> carries one attr per lowercased SYNTHPARAMETERS enum name, values
 * already engine-space) and the engine enum (src/dsp/Engine/Params.h), and
 * emits src/dsp/factory_bank.h:
 *
 *     static const nm_factory_preset_t NM_FACTORY_BANK[NM_FACTORY_COUNT] = {
 *         { "name", { <NUMPARAM engine-space floats, indexed by enum> } }, ...
 *     };
 *
 * Attribute values are written verbatim into programData[enumIndex]; no display
 * conversion. Attrs with no enum slot (none expected) are ignored; enum slots
 * with no attr stay 0.0f.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..');
const XML  = join(repo, 'tools/factory/tal_factory_bank.xml');
const ENUM = join(repo, 'src/dsp/Engine/Params.h');
const OUT  = join(repo, 'src/dsp/factory_bank.h');

/* ---- parse the SYNTHPARAMETERS enum -> { NAME: index } up to NUMPARAM ---- */
function parseEnum(src) {
  const body = src.slice(src.indexOf('enum SYNTHPARAMETERS'));
  const open = body.indexOf('{');
  const close = body.indexOf('}');
  const inner = body.slice(open + 1, close);
  const map = {};
  let idx = 0;
  for (let tok of inner.split(',')) {
    tok = tok.replace(/\/\/.*$/gm, '').trim();       // strip line comments
    if (!tok) continue;
    const m = tok.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*(=\s*(\d+))?$/);
    if (!m) continue;
    if (m[3] !== undefined) idx = parseInt(m[3], 10); // explicit "= N"
    map[m[1]] = idx;
    idx++;
  }
  return map;
}

const enumMap = parseEnum(readFileSync(ENUM, 'utf8'));
const NUMPARAM = enumMap['NUMPARAM'];
if (!NUMPARAM) throw new Error('could not resolve NUMPARAM from Params.h');

/* ---- parse the XML bank (attribute regex; values are plain floats/ints) ---- */
const xml = readFileSync(XML, 'utf8');
const progRe = /<program\b([^>]*)\/?>/g;
const attrRe = /([A-Za-z0-9]+)\s*=\s*"([^"]*)"/g;

const presets = [];
const unmapped = new Set();
let pm;
while ((pm = progRe.exec(xml)) !== null) {
  const attrs = {};
  let am;
  attrRe.lastIndex = 0;
  while ((am = attrRe.exec(pm[1])) !== null) attrs[am[1]] = am[2];

  const data = new Array(NUMPARAM).fill(0);
  let name = attrs['programname'] || `Program ${presets.length + 1}`;
  name = name                                    // decode XML entities
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(+d))
    .replace(/&amp;/g, '&');
  for (const [k, v] of Object.entries(attrs)) {
    if (k === 'programname') continue;
    const idx = enumMap[k.toUpperCase()];
    if (idx === undefined) { unmapped.add(k); continue; }
    data[idx] = parseFloat(v);
  }

  /* FILTERTYPE version skew: these v1.6 presets encode filtertype in a 10-item
   * combo scheme (value = k/9, k = 0..9), but the vendored engine now has 12
   * filter types (getNumComboBoxItems == 12) — Moog + Moog2 were appended after
   * these presets were saved. The first 10 filters are identical, so preserve
   * the intended filter: decode the authored index k = round(v*9) and re-encode
   * for the 12-item scheme as k/11, so calcComboBoxValue(v,12) picks the same
   * filter the preset meant (verified: KB Big Synth 0.444 -> HP24, matching the
   * old bank). Every OTHER combo param's item count is unchanged (osc waves 3/5,
   * LFO dests 8, free dest 6, porta 3, voices 6), so only filtertype is remapped. */
  const ftIdx = enumMap['FILTERTYPE'];
  if (ftIdx !== undefined) {
    const k = Math.round(data[ftIdx] * 9);   // authored combo index (10-item)
    data[ftIdx] = k / 11;                     // 12-item normalized, same filter
  }

  presets.push({ name, data });
}

if (presets.length === 0)
  console.warn(`[gen] warning: no <program> elements found in ${XML}`);
if (unmapped.size)
  console.warn(`[gen] warning: unmapped attrs (ignored): ${[...unmapped].join(', ')}`);

/* ---- emit the header ---- */
const cName = (s) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
const f = (x) => {
  if (!isFinite(x)) return '0.0f';
  let s = Number(x).toPrecision(9);
  if (!/[.eE]/.test(s)) s += '.0';
  return s + 'f';
};

let out = `/* factory_bank.h — GENERATED by tools/gen_factory_bank.mjs. DO NOT EDIT.
 *
 * TAL Noisemaker's ${presets.length} factory programs, engine-space, indexed by
 * SYNTHPARAMETERS. Regenerate: node tools/gen_factory_bank.mjs
 *
 * Programs (c) 2005-2010 Patrick Kunz, TAL / Togu Audio Line. GPL-2.0.
 */
#ifndef NM_FACTORY_BANK_H
#define NM_FACTORY_BANK_H

typedef struct { const char *name; float programData[${NUMPARAM}]; } nm_factory_preset_t;

#define NM_FACTORY_COUNT ${presets.length}

static const nm_factory_preset_t NM_FACTORY_BANK[NM_FACTORY_COUNT] = {
`;

for (const p of presets) {
  out += `  { "${cName(p.name)}", { ${p.data.map(f).join(', ')} } },\n`;
}
out += `};\n\n#endif /* NM_FACTORY_BANK_H */\n`;

writeFileSync(OUT, out);
console.log(`[gen] wrote ${OUT} (${presets.length} presets, ${NUMPARAM} params each)`);
