#!/usr/bin/env node
/*
 * gen_factory_splines.mjs — bake TAL Noisemaker's per-preset Envelope Editor
 * spline shapes into a C header the wrapper #includes.
 *
 * Reads the vendored plain-XML bank (tools/factory/tal_factory_bank.xml). Each
 * <program> carries a <splinePoints> child block of <splinePoint .../> elements
 * (many programs have an empty <splinePoints />). Programs are emitted in the
 * SAME order as gen_factory_bank.mjs, so NM_FACTORY_SPLINES[i] lines up with
 * NM_FACTORY_BANK[i].
 *
 * Emits src/dsp/factory_splines.h:
 *   typedef struct { int isStart, isEnd; float cx, cy, clx, cly, crx, cry; } nm_spline_point_t;
 *   typedef struct { int count; const nm_spline_point_t *points; } nm_spline_set_t;
 *   static const nm_spline_point_t NM_SPLINE_<i>[] = { ... };  // only for non-empty
 *   static const nm_spline_set_t NM_FACTORY_SPLINES[N] = { {count, ptr}, ... };
 *
 * Envelope shapes (c) 2005-2010 Patrick Kunz, TAL / Togu Audio Line. GPL-2.0.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..');
const XML  = join(repo, 'tools/factory/tal_factory_bank.xml');
const OUT  = join(repo, 'src/dsp/factory_splines.h');

const xml = readFileSync(XML, 'utf8');

/* Match each <program ...> ... </program> block (programs have a splinePoints
 * child, so they are never self-closed). */
const progRe = /<program\b[^>]*>([\s\S]*?)<\/program>/g;
const spRe   = /<splinePoint\b([^>]*?)\/?>/g;
const attrRe = /([A-Za-z0-9]+)\s*=\s*"([^"]*)"/g;

function attrs(s) {
  const o = {};
  let m;
  attrRe.lastIndex = 0;
  while ((m = attrRe.exec(s)) !== null) o[m[1]] = m[2];
  return o;
}

const presets = [];
let pm;
while ((pm = progRe.exec(xml)) !== null) {
  const body = pm[1];
  const pts = [];
  let sm;
  spRe.lastIndex = 0;
  while ((sm = spRe.exec(body)) !== null) {
    const a = attrs(sm[1]);
    pts.push({
      isStart: parseInt(a.isStartPoint || '0', 10) ? 1 : 0,
      isEnd:   parseInt(a.isEndPoint   || '0', 10) ? 1 : 0,
      cx:  parseFloat(a.centerPointX),
      cy:  parseFloat(a.centerPointY),
      clx: parseFloat(a.controlPointLeftX),
      cly: parseFloat(a.controlPointLeftY),
      crx: parseFloat(a.controlPointRightX),
      cry: parseFloat(a.controlPointRightY),
    });
  }
  presets.push(pts);
}

if (presets.length === 0)
  console.warn(`[gen] warning: no <program> elements found in ${XML}`);

const f = (x) => {
  if (!isFinite(x)) return '0.0f';
  let s = Number(x).toPrecision(9);
  if (!/[.eE]/.test(s)) s += '.0';
  return s + 'f';
};

let nonEmpty = 0;
let out = `/* factory_splines.h — GENERATED by tools/gen_factory_splines.mjs. DO NOT EDIT.
 *
 * TAL Noisemaker's per-preset Envelope Editor spline shapes, in the same order
 * as factory_bank.h. Regenerate: node tools/gen_factory_splines.mjs
 *
 * Envelope shapes (c) 2005-2010 Patrick Kunz, TAL / Togu Audio Line. GPL-2.0.
 */
#ifndef NM_FACTORY_SPLINES_H
#define NM_FACTORY_SPLINES_H

typedef struct { int isStart, isEnd; float cx, cy, clx, cly, crx, cry; } nm_spline_point_t;
typedef struct { int count; const nm_spline_point_t *points; } nm_spline_set_t;

`;

presets.forEach((pts, i) => {
  if (pts.length > 0) {
    nonEmpty++;
    out += `static const nm_spline_point_t NM_SPLINE_${i}[] = {\n`;
    for (const p of pts) {
      out += `  { ${p.isStart}, ${p.isEnd}, ${f(p.cx)}, ${f(p.cy)}, ${f(p.clx)}, ${f(p.cly)}, ${f(p.crx)}, ${f(p.cry)} },\n`;
    }
    out += `};\n`;
  }
});

out += `\nstatic const nm_spline_set_t NM_FACTORY_SPLINES[${presets.length}] = {\n`;
presets.forEach((pts, i) => {
  if (pts.length > 0) out += `  { ${pts.length}, NM_SPLINE_${i} },\n`;
  else                out += `  { 0, 0 },\n`;
});
out += `};\n\n#endif /* NM_FACTORY_SPLINES_H */\n`;

writeFileSync(OUT, out);
console.log(`[gen] wrote ${OUT} (${presets.length} presets, ${nonEmpty} with non-empty splines)`);
