/* GENERATED by schwung-canvaskit v34 — DO NOT EDIT THIS FILE.
 * Source of truth: the module's canvas config + the kit core. Rebuild with:
 *   node ../../schwung-canvaskit/build.mjs canvas.config.js <this file>
 * Chassis: movy-hybrid Bank Editor (widget language adapted from
 * schwung-movy, MIT (c) 2026 megadake; fonts via echidna/davebox mcufont).
 * Loaded by the host as canvas.js#bank_editor. Jog = banks (no overlay);
 * SHIFT+jog = section picker; knobs CC 71-78 edit the active bank. */
(function () {

/* ==== schwung-canvaskit core: prelude ====
 * Fonts, pure input helpers, and the cell-descriptor constructors a module's
 * canvas.config.js uses to build its banks. Emitted BEFORE the config so the
 * constructors are in scope there; the engine (everything reading CONFIG)
 * is emitted after. See README.md for the config contract. */

/* Tunables a config may reassign at its top, BEFORE building banks:
 *   KIT_PARAM_MAX   — native range max for continuous params (obxd 100, 0..255 engines 255)
 *   KIT_SENS        — detents per step for CONTINUOUS cells
 *   KIT_PICK_SENS   — detents per step for PICK cells
 *   KIT_DELIB_SENS  — detents per step for DELIBERATE cells
 *
 * ---- Knob response: three classes, one feel each (davebox's model) ----
 * Ported from schwung-davebox's 2026-07-18 unified pass, which replaced ~20
 * hand-tuned per-knob speeds. Every cell falls in exactly one class:
 *
 *   CONTINUOUS (uni/bip/fader) — KIT_SENS. Deliberately LEFT at movy's feel:
 *     a large continuous sweep wants to move. Slow turning still yields ±1 so
 *     exact dialing is always possible.
 *   PICK (enums >2 options, lengths, directions, targets, octaves, small
 *     counts) — KIT_PICK_SENS. Never accelerated, and they CLAMP rather than
 *     wrap: an accidental extra detent shouldn't roll past the end.
 *   DELIBERATE (toggles, 2-option enums, one-shot/destructive actions) —
 *     KIT_DELIB_SENS, the slowest. An accidental brush must not fire it.
 *
 * Rule of thumb for a custom cell: a range of <= 16 discrete values is PICK,
 * not continuous — digits are what the user is reading, so each one should
 * cost a deliberate amount of travel. */
let KIT_PARAM_MAX = 100;
let KIT_SENS = 2;         // continuous — movy's feel, kept
let KIT_PICK_SENS = 6;    // davebox KNOB_PICK
let KIT_DELIB_SENS = 12;  // davebox KNOB_DELIB


/* ---- pure input helpers (unit-tested off-device) ---- */

/* Relative-encoder sign: d2 1..63 = CW (+1), 65..127 = CCW (-1), else 0. */
function dirFromCC(d2) {
  if (d2 >= 1 && d2 <= 63) return 1;
  if (d2 >= 65 && d2 <= 127) return -1;
  return 0;
}

/* Clamp a bank index into [0, count-1]. */
function clampBank(idx, count) {
  if (idx < 0) return 0;
  if (idx > count - 1) return count - 1;
  return idx;
}

/* Encoder accumulator: count detents until |accum| reaches sens, then fire+reset.
 * A direction reversal discards the pending accumulation first (davebox feel). */
function accumStep(accum, dir, sens) {
  if ((accum > 0 && dir < 0) || (accum < 0 && dir > 0)) accum = 0;
  accum += dir;
  if (Math.abs(accum) >= sens) return { accum: 0, fire: true };
  return { accum: accum, fire: false };
}

/* Is SHIFT held? On device the shim does NOT forward CC 49 to shadow_ui in
 * chain-edit (its CC allowlist is 14/3/51/40-43/71-78/88), but it DOES sync
 * shift into SHM, and shadow_ui exposes it to this QuickJS context as
 * shadow_get_shift_held(). Poll that; fall back to CC-49 tracking (s.shift)
 * off-device (previewer/tests) — where the binding doesn't exist. */
function shiftHeld(s) {
  if (typeof shadow_get_shift_held === "function") return !!shadow_get_shift_held();
  return s.shift;
}

/* ---- mcufont: 5x5 monospace bitmap font (via the Echidna canvas, itself
 * from schwung-davebox assets/fonts/mcufont.h) ----
 * Rendered as flat 1-bit pixels via ctx.setPixel; the editor's draw()
 * overrides ctx.print/ctx.measureText with these, so all layout code renders
 * in this font. Uppercase only; 5px glyph + 1px gap = 6px advance. */
var PF_GLYPH_W = 5, PF_GLYPH_H = 5, PF_ADVANCE = 6;
var PF_FONT = {
  "A": ["01110", "10001", "11111", "10001", "10001"],
  "B": ["11110", "10001", "11110", "10001", "11110"],
  "C": ["01111", "10000", "10000", "10000", "01111"],
  "D": ["11110", "10001", "10001", "10001", "11110"],
  "E": ["11111", "10000", "11100", "10000", "11111"],
  "F": ["11111", "10000", "11100", "10000", "10000"],
  "G": ["01111", "10000", "10011", "10001", "01111"],
  "H": ["10001", "10001", "11111", "10001", "10001"],
  "I": ["11111", "00100", "00100", "00100", "11111"],
  "J": ["11111", "00010", "00010", "10010", "01100"],
  "K": ["10010", "10100", "11000", "10100", "10010"],
  "L": ["10000", "10000", "10000", "10000", "11111"],
  "M": ["11111", "10101", "10101", "10001", "10001"],
  "N": ["10001", "11001", "10101", "10011", "10001"],
  "O": ["01110", "10001", "10001", "10001", "01110"],
  "P": ["11110", "10001", "11110", "10000", "10000"],
  "Q": ["01110", "10001", "10001", "10010", "01101"],
  "R": ["11110", "10001", "11110", "10010", "10001"],
  "S": ["01111", "10000", "01110", "00001", "11110"],
  "T": ["11111", "00100", "00100", "00100", "00100"],
  "U": ["10001", "10001", "10001", "10001", "01110"],
  "V": ["10001", "10001", "01010", "01010", "00100"],
  "W": ["10001", "10001", "10101", "10101", "11011"],
  "X": ["10001", "01010", "00100", "01010", "10001"],
  "Y": ["10001", "01010", "00100", "00100", "00100"],
  "Z": ["11111", "00010", "00100", "01000", "11111"],
  "0": ["01110", "10001", "10101", "10001", "01110"],
  "1": ["01100", "10100", "00100", "00100", "11111"],
  "2": ["01110", "10001", "00110", "01000", "11111"],
  "3": ["11111", "00001", "01110", "00001", "11110"],
  "4": ["10010", "10010", "11111", "00010", "00010"],
  "5": ["11111", "10000", "01110", "00001", "11110"],
  "6": ["01110", "10000", "11110", "10001", "01110"],
  "7": ["11111", "00010", "00100", "01000", "01000"],
  "8": ["01110", "10001", "01110", "10001", "01110"],
  "9": ["11111", "10001", "11111", "00001", "00001"],
  " ": ["00000", "00000", "00000", "00000", "00000"],
  "-": ["00000", "00000", "01110", "00000", "00000"],
  "+": ["00000", "00100", "01110", "00100", "00000"],
  ".": ["00000", "00000", "00000", "00000", "01000"],
  ":": ["00000", "01000", "00000", "01000", "00000"],
  "/": ["00001", "00010", "00100", "01000", "10000"],
  ">": ["10000", "01000", "00100", "01000", "10000"]
};

/* Width in px of `text` in the pixel-font (no trailing gap). */
function pfWidth(text) {
  return Math.max(0, String(text).length * PF_ADVANCE - 1);
}

/* Draw `text` at (x,y) top-left in `color` (0/1) by plotting each on-pixel via
 * ctx.setPixel — the ctx.print replacement. Uppercased; missing chars -> space. */
function pfPrint(ctx, x, y, text, color) {
  var s = String(text).toUpperCase();
  var v = color ? 1 : 0;
  var ox0 = Math.round(x), oy = Math.round(y);
  for (var i = 0; i < s.length; i++) {
    var rows = PF_FONT[s[i]] || PF_FONT[" "];
    var ox = ox0 + i * PF_ADVANCE;
    for (var r = 0; r < PF_GLYPH_H; r++) {
      var row = rows[r];
      for (var c = 0; c < PF_GLYPH_W; c++) {
        if (row[c] === "1") ctx.setPixel(ox + c, oy + r, v);
      }
    }
  }
}

/* ---- header font: "6x6 Pixel Font" by asciimario
 * (fontstruct.com/fontstructions/show/821131, CC BY-NC 3.0 — NOTE: the
 * only non-MIT/CC0 asset in the kit) — a chunky 6x6 monospace pixel font,
 * rasterized from the OTF at its native grid (16px render, 2x downsample).
 * Uppercase-only (lowercase maps to caps; drawChrome uppercases anyway);
 * : - + < > / , % ? ( ) are hand-drawn in matching style (absent from the
 * font's cmap). Glyph format: [advance, ...6 rowBits] (advance includes
 * 1px spacing), bit0 = leftmost; [n] alone = blank; null = unmapped.
 * Used by drawChrome for the header text. ---- */
var HDR_G = [
  [7], [7,12,12,12,12,0,12], null, null, null, [7,51,48,12,12,3,51], null, null,
  [4,6,3,3,3,3,6], [4,3,6,6,6,6,3], null, [7,0,12,63,63,12,0], [7,0,0,0,0,12,4], [7,0,0,30,30,0,0], [7,0,0,0,0,12,12], [7,48,48,12,12,3,3],
  [7,30,51,59,55,51,30], [7,12,14,12,12,12,30], [7,30,51,48,30,3,63], [7,30,48,28,48,51,30], [7,24,28,30,27,63,24], [7,31,3,31,48,51,30], [7,30,3,31,51,51,30], [7,63,51,48,24,12,12],
  [7,30,51,30,51,51,30], [7,30,51,51,62,48,30], [7,12,12,0,0,12,12], null, [7,48,12,3,3,12,48], null, [7,3,12,48,48,12,3], [7,30,51,24,12,0,12],
  null, [7,30,51,51,63,51,51], [7,31,51,31,51,51,31], [7,30,51,3,3,51,30], [7,31,51,51,51,51,31], [7,63,3,31,3,3,63], [7,63,3,3,31,3,3], [7,30,51,3,59,51,62],
  [7,51,51,63,51,51,51], [7,30,12,12,12,12,30], [7,56,48,48,48,51,30], [7,51,27,15,15,27,51], [7,3,3,3,3,3,63], [7,35,55,63,43,35,35], [7,35,39,47,59,51,35], [7,30,51,51,51,51,30],
  [7,31,51,51,31,3,3], [7,30,51,51,59,19,46], [7,31,51,51,31,51,51], [7,30,3,30,48,51,30], [7,63,12,12,12,12,12], [7,51,51,51,51,51,30], [7,51,51,51,51,30,12], [7,35,35,43,63,55,35],
  [7,51,51,30,30,51,51], [7,51,51,51,30,12,12], [7,63,56,28,14,7,63], null, null, null, null, null,
  null, [7,30,51,51,63,51,51], [7,31,51,31,51,51,31], [7,30,51,3,3,51,30], [7,31,51,51,51,51,31], [7,63,3,31,3,3,63], [7,63,3,3,31,3,3], [7,30,51,3,59,51,62],
  [7,51,51,63,51,51,51], [7,30,12,12,12,12,30], [7,56,48,48,48,51,30], [7,51,27,15,15,27,51], [7,3,3,3,3,3,63], [7,35,55,63,43,35,35], [7,35,39,47,59,51,35], [7,30,51,51,51,51,30],
  [7,31,51,51,31,3,3], [7,30,51,51,59,19,46], [7,31,51,51,31,51,51], [7,30,3,30,48,51,30], [7,63,12,12,12,12,12], [7,51,51,51,51,51,30], [7,51,51,51,51,30,12], [7,35,35,43,63,55,35],
  [7,51,51,30,30,51,51], [7,51,51,51,30,12,12], [7,63,56,28,14,7,63], null, null, null, null
];

/* TRUE lowercase 'd' and 't' — the only two in this font. Everything else in
 * the lowercase range duplicates its capital (it's a caps design), but a
 * capital D is a 0 with the diagonal removed, so a dotted "1/64D" reads as
 * "1/640" in a fraction read-out. Triplet/dotted suffixes therefore need real
 * minuscules: 'd' = bowl + right ascender, 't' = stem + crossbar + tail.
 * 6 columns, 6 rows, bit0 = leftmost — same encoding as HDR_G above. */
HDR_G[0x64 - 0x20] = [7, 48, 48, 62, 51, 51, 62];   /* 'd' */
HDR_G[0x74 - 0x20] = [7, 12, 30, 12, 12, 12, 28];   /* 't' */

function hdrGlyph(cp) { return (cp < 0x20 || cp > 0x7E) ? null : HDR_G[cp - 0x20]; }

/* Width of `text` in the header font (advances include spacing; drop the
 * trailing 1px). */
function hdrWidth(text) {
  var s = String(text), w = 0;
  for (var i = 0; i < s.length; i++) {
    var g = hdrGlyph(s.charCodeAt(i));
    w += g ? g[0] : 7;
  }
  return Math.max(0, w - 1);
}

function hdrPrint(ctx, x, y, text, color) {
  var s = String(text), cx = Math.round(x), oy = Math.round(y);
  var v = color ? 1 : 0;
  for (var i = 0; i < s.length; i++) {
    var g = hdrGlyph(s.charCodeAt(i));
    if (!g) { cx += 7; continue; }
    for (var r = 0; r < 6; r++) {
      var bits = g[1 + r] || 0;
      for (var c = 0; c < 15; c++) if (bits & (1 << c)) ctx.setPixel(cx + c, oy + r, v);
    }
    cx += g[0];
  }
}

/* ---- movy main font (proportional, 5px tall; ported from schwung-movy
 * src/font/glyphs.ts + blit.ts, MIT, (c) 2026 megadake) — used for the
 * param LABEL strips (and their touched-value swap), the movy look.
 * Glyph format: [advance, yOff, w, h, ...rowBits], bit0 = leftmost pixel;
 * inter-glyph gap is -1 (glyphs tuck together). ASCII 0x20-0x7E; movy's
 * lowercase shares the uppercase shapes. ---- */
var MV_G = [
  [6, 0, 0, 0],                                  // ' '
  [3, 0, 3, 5, 2, 2, 2, 0, 2],                   // '!'
  [5, 0, 5, 2, 10, 10],                          // '"'
  [7, 0, 7, 5, 20, 62, 20, 62, 20],              // '#'
  [7, 0, 7, 5, 60, 10, 28, 40, 30],              // '$'
  [5, 0, 5, 5, 10, 8, 4, 2, 10],                 // '%'
  [5, 0, 5, 5, 4, 10, 4, 10, 12],                // '&'
  [3, 0, 3, 2, 2, 2],                            // "'"
  [4, 0, 4, 5, 4, 2, 2, 2, 4],                   // '('
  [4, 0, 4, 5, 2, 4, 4, 4, 2],                   // ')'
  [5, 1, 5, 3, 10, 4, 10],                       // '*'
  [5, 2, 5, 3, 4, 14, 4],                        // '+'
  [4, 4, 4, 3, 6, 4, 2],                         // ','
  [5, 3, 5, 1, 14],                              // '-'
  [3, 4, 3, 1, 2],                               // '.'
  [5, 0, 5, 5, 8, 8, 4, 2, 2],                   // '/'
  [6, 0, 6, 5, 30, 18, 18, 18, 30],              // '0'
  [5, 0, 5, 5, 6, 4, 4, 4, 14],                  // '1'
  [6, 0, 6, 5, 30, 16, 30, 2, 30],               // '2'
  [6, 0, 6, 5, 30, 16, 28, 16, 30],              // '3'
  [6, 0, 6, 5, 18, 18, 30, 16, 16],              // '4'
  [6, 0, 6, 5, 30, 2, 30, 16, 30],               // '5'
  [6, 0, 6, 5, 30, 2, 30, 18, 30],               // '6'
  [6, 0, 6, 5, 30, 16, 8, 4, 4],                 // '7'
  [6, 0, 6, 5, 30, 18, 30, 18, 30],              // '8'
  [6, 0, 6, 5, 30, 18, 30, 16, 30],              // '9'
  [4, 1, 4, 3, 4, 0, 4],                         // ':'
  [4, 1, 4, 4, 4, 0, 4, 2],                      // ';'
  [5, 0, 5, 5, 8, 4, 2, 4, 8],                   // '<'
  [5, 2, 5, 3, 14, 0, 14],                       // '='
  [5, 0, 5, 5, 2, 4, 8, 4, 2],                   // '>'
  [5, -1, 5, 6, 6, 8, 4, 4, 0, 4],               // '?'
  [7, 0, 7, 5, 28, 32, 44, 42, 28],              // '@'
  [6, 0, 6, 5, 12, 18, 30, 18, 18],              // 'A'
  [6, 0, 6, 5, 14, 18, 14, 18, 14],              // 'B'
  [6, 0, 6, 5, 12, 18, 2, 18, 12],               // 'C'
  [6, 0, 6, 5, 14, 18, 18, 18, 14],              // 'D'
  [6, 0, 6, 5, 30, 2, 14, 2, 30],                // 'E'
  [6, 0, 6, 5, 30, 2, 14, 2, 2],                 // 'F'
  [6, 0, 6, 5, 12, 2, 26, 18, 12],               // 'G'
  [6, 0, 6, 5, 18, 18, 30, 18, 18],              // 'H'
  [3, 0, 3, 5, 2, 2, 2, 2, 2],                   // 'I'
  [5, 0, 5, 5, 8, 8, 8, 10, 6],                  // 'J'
  [5, 0, 5, 5, 10, 10, 6, 10, 10],               // 'K'
  [6, 0, 6, 5, 2, 2, 2, 2, 30],                  // 'L'
  [7, 0, 7, 5, 30, 42, 42, 34, 34],              // 'M'
  [6, 0, 6, 5, 12, 18, 18, 18, 18],              // 'N'
  [6, 0, 6, 5, 12, 18, 18, 18, 12],              // 'O'
  [6, 0, 6, 5, 14, 18, 18, 14, 2],               // 'P'
  [6, 0, 6, 5, 12, 18, 18, 26, 28],              // 'Q'
  [6, 0, 6, 5, 14, 18, 18, 14, 18],              // 'R'
  [6, 0, 6, 5, 28, 2, 12, 16, 14],               // 'S'
  [5, 0, 5, 5, 14, 4, 4, 4, 4],                  // 'T'
  [6, 0, 6, 5, 18, 18, 18, 18, 12],              // 'U'
  [6, 0, 6, 5, 18, 18, 18, 10, 6],               // 'V'
  [7, 0, 7, 5, 34, 34, 42, 42, 30],              // 'W'
  [5, 0, 5, 5, 10, 10, 4, 10, 10],               // 'X'
  [6, 0, 6, 5, 18, 18, 28, 16, 14],              // 'Y'
  [6, 0, 6, 5, 30, 16, 12, 2, 30],               // 'Z'
  [4, 0, 4, 5, 6, 2, 2, 2, 6],                   // '['
  [5, 0, 5, 5, 2, 2, 4, 8, 8],                   // '\\'
  [4, 0, 4, 5, 6, 4, 4, 4, 6],                   // ']'
  [5, 0, 5, 2, 4, 10],                           // '^'
  [6, 5, 6, 1, 30],                              // '_'
  [4, 0, 4, 2, 2, 4],                            // '`'
  [6, 0, 6, 5, 12, 18, 30, 18, 18],              // 'a'
  [6, 0, 6, 5, 14, 18, 14, 18, 14],              // 'b'
  [6, 0, 6, 5, 12, 18, 2, 18, 12],               // 'c'
  [6, 0, 6, 5, 14, 18, 18, 18, 14],              // 'd'
  [6, 0, 6, 5, 30, 2, 14, 2, 30],                // 'e'
  [6, 0, 6, 5, 30, 2, 14, 2, 2],                 // 'f'
  [6, 0, 6, 5, 12, 2, 26, 18, 12],               // 'g'
  [6, 0, 6, 5, 18, 18, 30, 18, 18],              // 'h'
  [3, 0, 3, 5, 2, 2, 2, 2, 2],                   // 'i'
  [5, 0, 5, 5, 8, 8, 8, 10, 6],                  // 'j'
  [5, 0, 5, 5, 10, 10, 6, 10, 10],               // 'k'
  [6, 0, 6, 5, 2, 2, 2, 2, 30],                  // 'l'
  [7, 0, 7, 5, 30, 42, 42, 34, 34],              // 'm'
  [6, 0, 6, 5, 12, 18, 18, 18, 18],              // 'n'
  [6, 0, 6, 5, 12, 18, 18, 18, 12],              // 'o'
  [6, 0, 6, 5, 14, 18, 18, 14, 2],               // 'p'
  [6, 0, 6, 5, 12, 18, 18, 26, 28],              // 'q'
  [6, 0, 6, 5, 14, 18, 18, 14, 18],              // 'r'
  [6, 0, 6, 5, 28, 2, 12, 16, 14],               // 's'
  [5, 0, 5, 5, 14, 4, 4, 4, 4],                  // 't'
  [6, 0, 6, 5, 18, 18, 18, 18, 12],              // 'u'
  [6, 0, 6, 5, 18, 18, 18, 10, 6],               // 'v'
  [7, 0, 7, 5, 34, 34, 42, 42, 30],              // 'w'
  [5, 0, 5, 5, 10, 10, 4, 10, 10],               // 'x'
  [6, 0, 6, 5, 18, 18, 28, 16, 30],              // 'y'
  [6, 0, 6, 5, 30, 16, 12, 2, 30],               // 'z'
  [5, 0, 5, 5, 12, 4, 2, 4, 12],                 // '{'
  [3, 0, 3, 5, 2, 2, 2, 2, 2],                   // '|'
  [5, 0, 5, 5, 6, 4, 8, 4, 6],                   // '}'
  [6, 0, 6, 2, 20, 10]                           // '~'
];

function mvGlyph(cp) { return (cp < 0x20 || cp > 0x7E) ? null : MV_G[cp - 0x20]; }

/* Width of `text` in the movy font (advance sum, -1px inter-glyph gap). */
function mvWidth(text) {
  var s = String(text), w = 0;
  for (var i = 0; i < s.length; i++) {
    var g = mvGlyph(s.charCodeAt(i));
    w += g ? g[0] : 5;
    if (i < s.length - 1) w -= 1;
  }
  return w;
}

function mvPrint(ctx, x, y, text, color) {
  var s = String(text), cx = Math.round(x), oy = Math.round(y);
  var v = color ? 1 : 0;
  for (var i = 0; i < s.length; i++) {
    var g = mvGlyph(s.charCodeAt(i));
    if (!g) { cx += 5; continue; }
    var yOff = g[1], w = g[2], h = g[3];
    for (var r = 0; r < h; r++) {
      var bits = g[4 + r];
      for (var c = 0; c < w; c++) if (bits & (1 << c)) ctx.setPixel(cx + c, oy + yOff + r, v);
    }
    cx += g[0];
    if (i < s.length - 1) cx -= 1;
  }
}

/* ---- big font: 13pt Nokia bitmap (ported from schwung-movy src/font/big.ts +
 * glyphs-big.ts, MIT, (c) 2026 megadake) — cap-height 11px, ~9px digits. This
 * is movy's own large numeric read-out ('preset' render style in
 * renderer/knob.ts, used there for Tempo / Swing / Root / Condition / Length /
 * Transpose). Glyph format: [advance, yOff, w, h, ...rowBits], bit0 = leftmost;
 * 1px inter-glyph gap (the source OTF leaves no side bearing). ---- */
var BIG_H = 11;
var BIG_GAP = 1;
var BIG_G = [
  [4, 0, 0, 0],// ' '
  [4, 0, 4, 11, 3, 3, 3, 3, 3, 3, 3, 3, 0, 3, 3],// '!'
  [7, 0, 7, 3, 27, 27, 9],// '"'
  [9, 1, 9, 10, 54, 54, 127, 127, 54, 54, 127, 127, 54, 54],// '#'
  [9, 0, 9, 12, 8, 62, 127, 11, 11, 63, 126, 104, 104, 127, 62, 8],// '$'
  [10, 0, 10, 11, 102, 101, 117, 51, 56, 24, 28, 204, 174, 166, 102],// '%'
  [10, 0, 10, 11, 30, 63, 3, 99, 254, 255, 99, 99, 99, 127, 62],// '&'
  [4, 0, 4, 3, 3, 3, 1],// "'"
  [6, 0, 6, 13, 12, 6, 6, 3, 3, 3, 3, 3, 3, 3, 6, 6, 12],// '('
  [6, 0, 6, 13, 3, 6, 6, 12, 12, 12, 12, 12, 12, 12, 6, 6, 3],// ')'
  [10, 2, 10, 9, 24, 24, 219, 255, 60, 255, 219, 24, 24],// '*'
  [8, 3, 8, 6, 12, 12, 63, 63, 12, 12],// '+'
  [5, 9, 5, 3, 6, 6, 3],// ','
  [7, 5, 7, 2, 31, 31],// '-'
  [4, 9, 4, 2, 3, 3],// '.'
  [6, 0, 6, 11, 12, 12, 12, 14, 6, 6, 6, 7, 3, 3, 3],// '/'
  [9, 0, 9, 11, 62, 127, 99, 99, 99, 99, 99, 99, 99, 127, 62],// '0'
  [8, 0, 8, 11, 48, 56, 60, 60, 48, 48, 48, 48, 48, 48, 48],// '1'
  [9, 0, 9, 11, 62, 127, 99, 96, 112, 56, 28, 14, 7, 127, 127],// '2'
  [9, 0, 9, 11, 62, 127, 99, 96, 60, 124, 96, 96, 99, 127, 62],// '3'
  [9, 0, 9, 11, 48, 56, 60, 54, 55, 51, 127, 127, 48, 48, 48],// '4'
  [9, 0, 9, 11, 63, 63, 3, 3, 63, 127, 96, 96, 99, 127, 62],// '5'
  [9, 0, 9, 11, 62, 127, 3, 63, 127, 99, 99, 99, 99, 127, 62],// '6'
  [9, 0, 9, 11, 127, 127, 48, 48, 24, 24, 12, 12, 12, 12, 12],// '7'
  [9, 0, 9, 11, 62, 127, 99, 99, 62, 127, 99, 99, 99, 127, 62],// '8'
  [9, 0, 9, 11, 62, 127, 99, 99, 99, 127, 126, 96, 99, 127, 62],// '9'
  [4, 5, 4, 6, 3, 3, 0, 0, 3, 3],// ':'
  [5, 5, 5, 7, 6, 6, 0, 0, 6, 6, 3],// ';'
  [8, 1, 8, 10, 48, 56, 28, 14, 7, 7, 14, 28, 56, 48],// '<'
  [7, 4, 7, 5, 31, 31, 0, 31, 31],// '='
  [8, 1, 8, 10, 3, 7, 14, 28, 56, 56, 28, 14, 7, 3],// '>'
  [9, 0, 9, 11, 62, 127, 99, 99, 120, 60, 12, 12, 0, 12, 12],// '?'
  [13, 0, 13, 11, 508, 1022, 1799, 1779, 1755, 1755, 2011, 1011, 7, 1022, 508],// '@'
  [9, 0, 9, 11, 62, 127, 99, 99, 99, 99, 99, 127, 127, 99, 99],// 'A'
  [9, 0, 9, 11, 63, 127, 99, 99, 63, 127, 99, 99, 99, 127, 63],// 'B'
  [9, 0, 9, 11, 62, 127, 3, 3, 3, 3, 3, 3, 3, 127, 62],// 'C'
  [9, 0, 9, 11, 63, 127, 99, 99, 99, 99, 99, 99, 99, 127, 63],// 'D'
  [9, 0, 9, 11, 127, 127, 3, 3, 31, 31, 3, 3, 3, 127, 127],// 'E'
  [9, 0, 9, 11, 127, 127, 3, 3, 31, 31, 3, 3, 3, 3, 3],// 'F'
  [9, 0, 9, 11, 62, 127, 3, 3, 115, 115, 99, 99, 99, 127, 126],// 'G'
  [9, 0, 9, 11, 99, 99, 99, 99, 127, 127, 99, 99, 99, 99, 99],// 'H'
  [4, 0, 4, 11, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],// 'I'
  [7, 0, 7, 11, 24, 24, 24, 24, 24, 24, 24, 24, 24, 31, 15],// 'J'
  [9, 0, 9, 11, 99, 115, 59, 31, 15, 7, 15, 31, 59, 115, 99],// 'K'
  [8, 0, 8, 11, 3, 3, 3, 3, 3, 3, 3, 3, 3, 63, 63],// 'L'
  [11, 0, 11, 11, 257, 387, 455, 495, 511, 443, 403, 387, 387, 387, 387],// 'M'
  [9, 0, 9, 11, 99, 99, 103, 103, 111, 111, 123, 123, 115, 115, 99],// 'N'
  [9, 0, 9, 11, 62, 127, 99, 99, 99, 99, 99, 99, 99, 127, 62],// 'O'
  [9, 0, 9, 11, 63, 127, 99, 99, 99, 127, 63, 3, 3, 3, 3],// 'P'
  [9, 0, 9, 12, 62, 127, 99, 99, 99, 99, 99, 99, 123, 127, 62, 96],// 'Q'
  [9, 0, 9, 11, 63, 127, 99, 99, 99, 63, 127, 99, 99, 99, 99],// 'R'
  [9, 0, 9, 11, 62, 127, 3, 3, 63, 126, 96, 96, 96, 127, 62],// 'S'
  [8, 0, 8, 11, 63, 63, 12, 12, 12, 12, 12, 12, 12, 12, 12],// 'T'
  [9, 0, 9, 11, 99, 99, 99, 99, 99, 99, 99, 99, 99, 127, 62],// 'U'
  [9, 0, 9, 11, 99, 99, 99, 99, 99, 99, 119, 54, 62, 28, 8],// 'V'
  [12, 0, 12, 11, 771, 771, 771, 771, 951, 438, 510, 510, 204, 204, 204],// 'W'
  [9, 0, 9, 11, 99, 99, 99, 54, 62, 28, 62, 54, 99, 99, 99],// 'X'
  [10, 0, 10, 11, 195, 195, 231, 102, 126, 60, 60, 24, 24, 24, 24],// 'Y'
  [9, 0, 9, 11, 127, 127, 96, 112, 56, 28, 14, 7, 3, 127, 127],// 'Z'
  [5, 0, 5, 13, 7, 7, 3, 3, 3, 3, 3, 3, 3, 3, 3, 7, 7],// '['
  [6, 0, 6, 11, 3, 3, 3, 7, 6, 6, 6, 14, 12, 12, 12],// '\\'
  [5, 0, 5, 13, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7],// ']'
  [5, 0, 5, 2, 2, 5],// '^'
  [9, 11, 9, 1, 127],// '_'
  [4, 0, 4, 2, 1, 2],// '`'
  [9, 3, 9, 8, 126, 127, 99, 99, 99, 99, 127, 126],// 'a'
  [9, 0, 9, 11, 3, 3, 3, 63, 127, 99, 99, 99, 99, 127, 63],// 'b'
  [8, 3, 8, 8, 30, 63, 3, 3, 3, 3, 63, 30],// 'c'
  [9, 0, 9, 11, 96, 96, 96, 126, 127, 99, 99, 99, 99, 127, 126],// 'd'
  [9, 3, 9, 8, 62, 127, 99, 127, 63, 3, 127, 62],// 'e'
  [7, 0, 7, 11, 28, 30, 6, 15, 15, 6, 6, 6, 6, 6, 6],// 'f'
  [9, 3, 9, 10, 126, 127, 99, 99, 99, 127, 126, 96, 126, 60],// 'g'
  [9, 0, 9, 11, 3, 3, 3, 63, 127, 99, 99, 99, 99, 99, 99],// 'h'
  [4, 0, 4, 11, 3, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3],// 'i'
  [6, 0, 6, 13, 12, 12, 0, 12, 12, 12, 12, 12, 12, 12, 12, 15, 7],// 'j'
  [9, 0, 9, 11, 3, 3, 3, 99, 115, 63, 31, 51, 51, 99, 99],// 'k'
  [4, 0, 4, 11, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],// 'l'
  [12, 3, 12, 8, 511, 1023, 819, 819, 819, 819, 819, 819],// 'm'
  [9, 3, 9, 8, 63, 127, 99, 99, 99, 99, 99, 99],// 'n'
  [9, 3, 9, 8, 62, 127, 99, 99, 99, 99, 127, 62],// 'o'
  [9, 3, 9, 10, 63, 127, 99, 99, 99, 99, 127, 63, 3, 3],// 'p'
  [9, 3, 9, 10, 126, 127, 99, 99, 99, 99, 127, 126, 96, 96],// 'q'
  [7, 3, 7, 8, 27, 31, 7, 3, 3, 3, 3, 3],// 'r'
  [8, 3, 8, 8, 62, 63, 3, 15, 60, 48, 63, 31],// 's'
  [6, 0, 6, 11, 6, 6, 6, 15, 15, 6, 6, 6, 6, 14, 12],// 't'
  [9, 3, 9, 8, 99, 99, 99, 99, 99, 99, 127, 126],// 'u'
  [9, 3, 9, 8, 99, 99, 99, 99, 119, 62, 28, 8],// 'v'
  [10, 3, 10, 8, 195, 195, 195, 219, 219, 255, 126, 102],// 'w'
  [9, 3, 9, 8, 99, 119, 62, 28, 28, 62, 119, 99],// 'x'
  [9, 3, 9, 10, 99, 99, 99, 99, 99, 127, 126, 96, 126, 60],// 'y'
  [9, 3, 9, 8, 127, 127, 56, 28, 14, 7, 127, 127],// 'z'
  [6, 0, 6, 13, 12, 6, 6, 6, 6, 6, 3, 6, 6, 6, 6, 6, 12],// '{'
  [4, 0, 4, 13, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],// '|'
  [6, 0, 6, 13, 3, 6, 6, 6, 6, 6, 12, 6, 6, 6, 6, 6, 3],// '}'
  [8, 6, 8, 3, 38, 63, 25],// '~'
];
function bigGlyph(cp) { return (cp < 0x20 || cp > 0x7E) ? null : BIG_G[cp - 0x20]; }

/* Tight punctuation: the source font gives these a full letter's advance, so a
 * decimal point or slash ate most of a digit's worth of a 32px cell. They
 * advance by their INK width and take no gap on their LEFT (free — every digit
 * carries ~2px of right side bearing). The gap on their RIGHT is kept: the next
 * glyph starts at its own left edge, so without it "0.25" reads as "0.2 5".
 * Keyed by codepoint. */
var BIG_TIGHT = { 0x2E: 2, 0x3A: 2, 0x2C: 3, 0x3B: 3, 0x2F: 5 };   /* . : , ; / */

/* Ink bounds per glyph, measured once: [leftmostCol, inkWidth]. Drives the
 * CONDENSED variant. */
var BIG_INK = BIG_G.map(function (g) {
  var w = g[2], h = g[3], lo = 99, hi = -1;
  for (var r = 0; r < h; r++) {
    var bits = g[4 + r];
    for (var c = 0; c < w; c++) if (bits & (1 << c)) { if (c < lo) lo = c; if (c > hi) hi = c; }
  }
  return hi < 0 ? [0, 0] : [lo, hi - lo + 1];
});

/* CONDENSED: same glyphs, same 11px height, advances trimmed to ink width + 1
 * (punctuation to exact ink) and the glyph shifted left onto its own ink. The
 * source is generously spaced — a digit is a 9px advance carrying 7px of ink —
 * so this buys ~15% with no loss of legibility, enough to hold a 4-character
 * value like "1/16" or a 5-character "1/16T" in a 32px cell. It is NOT a
 * smaller font: mixed with normal spacing it reads as tracking, not two sizes. */
function bigAdv(cp, g, cond) {
  var ink = BIG_INK[cp - 0x20][1];
  if (!cond) return BIG_TIGHT[cp] !== undefined ? BIG_TIGHT[cp] : g[0];
  if (!ink) return g[0];
  return BIG_TIGHT[cp] !== undefined ? ink : ink + 1;
}
function bigGapAt(a, b) { return BIG_TIGHT[b] !== undefined ? 0 : BIG_GAP; }

/* Width of `text` in the big font (no trailing gap). `cond` = condensed. */
function bigWidth(text, cond) {
  var s = String(text), w = 0;
  for (var i = 0; i < s.length; i++) {
    var cp = s.charCodeAt(i), g = bigGlyph(cp);
    w += g ? bigAdv(cp, g, cond) : 7;
    if (i < s.length - 1) w += bigGapAt(cp, s.charCodeAt(i + 1));
  }
  return w;
}

function bigPrint(ctx, x, y, text, color, cond) {
  var s = String(text), cx = Math.round(x), oy = Math.round(y);
  var v = color ? 1 : 0;
  for (var i = 0; i < s.length; i++) {
    var cp = s.charCodeAt(i), g = bigGlyph(cp);
    if (!g) { cx += 7; continue; }
    var yOff = g[1], w = g[2], h = g[3];
    var shift = cond ? BIG_INK[cp - 0x20][0] : 0;   /* sit on the ink */
    for (var r = 0; r < h; r++) {
      var bits = g[4 + r];
      for (var c = 0; c < w; c++) if (bits & (1 << c)) ctx.setPixel(cx + c - shift, oy + yOff + r, v);
    }
    cx += bigAdv(cp, g, cond);
    if (i < s.length - 1) cx += bigGapAt(cp, s.charCodeAt(i + 1));
  }
}

/* Largest form of `text` that fits `maxW`: normal spacing, else condensed,
 * else null (caller drops to the label font). Returns { w, cond }. */
function bigFit(text, maxW) {
  var n = bigWidth(text, false);
  if (n <= maxW) return { w: n, cond: false };
  var c = bigWidth(text, true);
  if (c <= maxW) return { w: c, cond: true };
  return null;
}

/* ---- 5x3 micro font (ported from schwung-movy src/font/glyphs5x3.ts, MIT,
 * (c) 2026 megadake) — used INSIDE the widget boxes (enum squares, value
 * squares), where the 6px-advance 5x5 font can't fit. Glyph format:
 * [advance, yOff, w, h, ...rowBits], bit0 = leftmost pixel. ---- */
var PF3_CHARS = " !\"'()+,-./:0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ%<>=?*";
var PF3_G = [
  [4,0,0,0],
  [4,0,3,5,1,1,1,0,1], [4,0,3,5,5,5,0,0,0], [4,0,3,5,2,2,0,0,0],
  [4,0,3,5,2,1,1,1,2], [4,0,3,5,1,2,2,2,1], [4,0,3,5,2,7,2,0,0],
  [4,0,3,5,0,0,3,3,2], [4,0,3,5,0,0,7,0,0], [4,0,3,5,0,0,0,3,3],
  [4,0,3,5,4,4,2,1,1], [4,0,3,5,3,3,0,3,3],
  [4,0,3,5,7,5,5,5,7], [4,0,3,5,2,3,2,2,7], [4,0,3,5,7,4,7,1,7],
  [4,0,3,5,7,4,6,4,7], [4,0,3,5,5,5,7,4,4], [4,0,3,5,7,1,7,4,7],
  [4,0,3,5,7,1,7,5,7], [4,0,3,5,7,4,4,4,4], [4,0,3,5,7,5,7,5,7],
  [4,0,3,5,7,5,7,4,7],
  [4,0,3,5,2,7,5,5,5], [4,0,3,5,7,5,3,5,7], [4,0,3,5,7,1,1,1,7],
  [4,0,3,5,3,5,5,5,3], [4,0,3,5,7,1,3,1,7], [4,0,3,5,7,1,3,1,1],
  [4,0,3,5,7,1,5,5,7], [4,0,3,5,5,5,7,5,5], [4,0,3,5,7,2,2,2,7],
  [4,0,3,5,4,4,4,5,7], [4,0,3,5,5,5,3,5,5], [4,0,3,5,1,1,1,1,7],
  [4,0,3,5,5,7,5,5,5], [4,0,3,5,5,3,5,5,5], [4,0,3,5,7,5,5,5,7],
  [4,0,3,5,7,5,7,1,1], [4,0,3,5,3,5,5,7,2], [4,0,3,5,7,5,3,5,5],
  [4,0,3,5,6,1,2,4,3], [4,0,3,5,7,2,2,2,2], [4,0,3,5,5,5,5,5,7],
  [4,0,3,5,5,5,5,5,2], [4,0,3,5,5,5,5,7,7], [4,0,3,5,5,5,2,5,5],
  [4,0,3,5,5,5,7,2,2], [4,0,3,5,7,4,2,1,7],
  [4,0,3,5,5,4,2,1,5], [4,0,3,5,4,2,1,2,4], [4,0,3,5,1,2,4,2,1],
  [4,0,3,5,7,0,7,0,0], [4,0,3,5,7,4,6,0,2], [4,0,3,5,2,7,2,5,0]
];

function pf3Glyph(ch) {
  var i = PF3_CHARS.indexOf(ch);
  return i >= 0 ? PF3_G[i] : null;
}
function pf3Width(text) {
  var s = String(text).toUpperCase(), w = 0;
  for (var i = 0; i < s.length; i++) { var g = pf3Glyph(s[i]); w += g ? g[0] : 4; }
  return w;
}
function pf3Print(ctx, x, y, text, color) {
  var s = String(text).toUpperCase(), cx = Math.round(x), oy = Math.round(y);
  var v = color ? 1 : 0;
  for (var i = 0; i < s.length; i++) {
    var g = pf3Glyph(s[i]);
    if (!g) { cx += 4; continue; }
    var yOff = g[1], w = g[2], h = g[3];
    for (var r = 0; r < h; r++) {
      var bits = g[4 + r];
      for (var c = 0; c < w; c++) if (bits & (1 << c)) ctx.setPixel(cx + c, oy + yOff + r, v);
    }
    cx += g[0];
  }
}

/* Split an enum value into two <=3-char lines for the enum square (movy's
 * enumSquareLines): word-split when possible, else a hard split. Configs can
 * sidestep bad auto-splits ("KEE/P") with per-option `sq` labels (enumc). */
function enumSquareLines(value) {
  var parts = String(value).toUpperCase().replace(/[_\-]/g, " ").trim().split(/\s+/);
  if (parts.length >= 2) return [parts[0].substring(0, 3), parts[1].substring(0, 3)];
  var w = parts[0];
  return [w.substring(0, 3), w.substring(3, 6)];
}

/* ---- cell descriptor constructors (native-int chain contract) ----
 * The config builds its banks from these. Each carries the `sens` of its
 * knob-response class (see the three classes at the top of this file), and
 * every discrete kind CLAMPS at its ends rather than wrapping — an accidental
 * extra detent shouldn't flip On back to Off. All read KIT_PARAM_MAX and the
 * sens tunables at CALL time, so a config that reassigns them must do so
 * BEFORE building its banks. */

const kToggleLabels = ["Off", "On"];

/* Continuous 0..KIT_PARAM_MAX, rendered as an arc knob. */
function uni(key, label) { return { key, label, kind: "unipolar", min: 0, max: KIT_PARAM_MAX, step: 1, sens: KIT_SENS }; }
/* Center-detent continuous (pan, tune): arc knob with a 12-o'clock tick;
 * value shows signed offset from center; center-out bar semantics. */
function bip(key, label) { return { key, label, kind: "bipolar", min: 0, max: KIT_PARAM_MAX, step: 1, sens: KIT_SENS, dflt: Math.round(KIT_PARAM_MAX / 2) }; }
/* On/Off toggle, rendered as a movy horizontal bar. */
function tog(key, label) { return { key, label, kind: "enum", min: 0, max: 1, step: 1, sens: KIT_DELIB_SENS, options: kToggleLabels }; }
/* Multi-option enum, rendered as a framed square + a scrolling list overlay
 * while touched. `sq` (optional): per-option single-line square labels. */
function enumc(key, label, options, sq) { return { key, label, kind: "enum", min: 0, max: options.length - 1, step: 1, sens: options.length <= 2 ? KIT_DELIB_SENS : KIT_PICK_SENS, options, sq }; }
/* Small signed range (+N display), rendered as a value square. */
function oct(key, label, lo, hi) { return { key, label, kind: "octave", min: lo, max: hi, step: 1, sens: KIT_PICK_SENS }; }
/* Small positive count, rendered as a value square. */
function count(key, label, lo, hi) { return { key, label, kind: "count", min: lo, max: hi, step: 1, sens: KIT_PICK_SENS }; }
/* Envelope-stage cell (use on `env: true` banks, cells 0-3 = A/D/S/R drive
 * the full-width envelope graphic; other fader cells render as a vbar). */
function fader(key, label) { return { key, label, kind: "fader", min: 0, max: KIT_PARAM_MAX, step: 1, sens: KIT_SENS }; }
/* Modulation-target slot that is currently NONE — a framed box with a drawn
 * diagonal cross (movy's xbox). Reads as "nothing routed here" at a glance;
 * use in place of an enum whose unset state deserves more than a "--". */
function xbox(key, label, options) { return { key, label, kind: "xbox", min: 0, max: (options ? options.length - 1 : 1), step: 1, sens: KIT_PICK_SENS, options: options || kToggleLabels }; }
/* Musical length drawn as a real stacked FRACTION in a framed square
 * (numerator / 1px rule / denominator, movy's length square). The alternative
 * to a big read-out for "1/16"-style values — pick whichever suits the param. */
function len(key, label, options) { return { key, label, kind: "len", min: 0, max: options.length - 1, step: 1, sens: KIT_PICK_SENS, options }; }
/* One-shot or RELATIVE control (davebox): the square shows "< >" at rest —
 * "turn either way" — and swaps to the live value while its knob is touched.
 * `oneWay: true` (destructive actions) keeps "< >" even when touched. */
function action(key, label, options, oneWay) { return { key, label, kind: "action", min: 0, max: (options ? options.length - 1 : 1), step: 1, sens: KIT_DELIB_SENS, options: options || kToggleLabels, oneWay: !!oneWay }; }
/* Playback direction as real arrows (davebox): 0 Fwd, 1 Bwd, 2 ping-pong out,
 * 3 ping-pong in. `options` supply the picker/label names. */
function dir(key, label, options) { return { key, label, kind: "dir", min: 0, max: 3, step: 1, sens: KIT_PICK_SENS, options: options || ["Fwd", "Bwd", "PPf", "PPb"] }; }
/* Empty grid slot (keeps knob positions aligned in dynamicCells layouts). */
function blank() { return { key: null, label: "", kind: "blank" }; }
/* Waveform-shape enum: like enumc, but the widget draws the selected shape's
 * actual waveform (shapeSample) instead of its name. `shapes` = one shape id
 * per option: "sine" | "tri" | "saw" | "square" | "sh" | "swishy". */
function wavesel(key, label, options, shapes) { return { key, label, kind: "waveenum", min: 0, max: options.length - 1, step: 1, sens: KIT_PICK_SENS, options, shapes }; }

/* Bipolar (-1..1) sample of an LFO shape at phase t (one cycle = 1). s&h and
 * swishy use fixed deterministic patterns so frames are stable (from
 * schwung-movy src/renderer/lfo-wave.ts, MIT (c) 2026 megadake). */
function shapeSample(shape, t) {
  var ph = t - Math.floor(t);
  switch (shape) {
    case "tri":
      if (ph < 0.25) return ph * 4;
      if (ph < 0.75) return 1 - (ph - 0.25) * 4;
      return -1 + (ph - 0.75) * 4;
    case "saw": return ph * 2 - 1;
    case "square": return ph < 0.5 ? 1 : -1;
    case "sh": {
      var steps = [0.3, -0.7, 0.85, -0.35];
      return steps[Math.floor(ph * steps.length) % steps.length];
    }
    case "swishy": {
      var pts = [0, 0.7, -0.4, 0.55, -0.8, 0.2, 0];
      var x = ph * (pts.length - 1);
      var i = Math.floor(x), f = x - i;
      return pts[i] + (pts[Math.min(i + 1, pts.length - 1)] - pts[i]) * f;
    }
    default: return Math.sin(ph * 2 * Math.PI); // sine
  }
}

/* Swappable clock for the step-editor playhead: prefer a host tempo clock
 * when present, else wall time. */
function nowMs() { return (typeof host_now_ms === "function") ? host_now_ms() : Date.now(); }


/* ==== module config (canvas.config.js) ==== */

/* Noisemaker canvas config for schwung-canvaskit (../schwung-canvaskit).
 * SOURCE for src/canvas.js — regenerate after editing:
 *   node ../schwung-canvaskit/build.mjs src/canvas.config.js src/canvas.js
 *
 * Grouping mirrors the TAL NoiseMaker desktop panels (LFO1/LFO2/OSC1/OSC2/
 * MASTER, FILTER + AMP with their ADSR sliders, and the Chorus/Crush/Reverb/
 * Delay effect strip). Uses the kit's visual models where the synth does:
 * wavesel (osc + LFO waveform shape boxes), filterViz (filter-response curve).
 *
 * Wire contract (src/dsp/noisemaker_plugin.cpp): all params are native ints —
 * continuous 0..100 (K_PCT / K_BIPOLAR centered at 50), enums exchange the
 * OPTION INDEX both ways. No per-cell codecs needed. */

KIT_PARAM_MAX = 100;

/* enum labels — order MUST match the wrapper's PARAMS[] option order. */
const FILT     = ["LP24","LP18","LP12","LP6","HP24","BP24","Notch","SV-LP","SV-HP","SV-BP","Moog","Moog2"];
const FILT_SQ  = ["L24","L18","L12","L6","H24","B24","Ntc","SVL","SVH","SVB","Mog","Mg2"];
/* filterViz curve shape per filter type. */
const FILT_MODES = ["lp","lp","lp","lp","hp","bp","notch","lp","hp","bp","lp","lp"];
const LDST1    = ["None","Filter","Osc1","Osc2","PW","FM","LFO2","Osc1+2"];
const LDST1_SQ = ["Non","Flt","Os1","Os2","PW","FM","LF2","O12"];
const LDST2    = ["None","Filter","Osc1","Osc2","PW","FM","LFO1","Osc1+2"];
const LDST2_SQ = ["Non","Flt","Os1","Os2","PW","FM","LF1","O12"];
const FDST     = ["Off","Filter","Osc1","Osc2","PW","FM"];
const FDST_SQ  = ["Off","Flt","Os1","Os2","PW","FM"];
const PMODE    = ["Off","Auto","On"];
const OSC1_WAVES = ["Saw","Pulse","Noise"];
const OSC1_SHAPES = ["saw","square","swishy"];
const OSC2_WAVES = ["Saw","Pulse","Tri","Sine","Noise"];
const OSC2_SHAPES = ["saw","square","tri","sine","swishy"];
const LFO_WAVES  = ["Sin","Tri","Saw","Sqr","S+H","Rnd"];
const LFO_SHAPES = ["sine","tri","saw","square","sh","swishy"];

const CONFIG = {
  name: "Noisemaker",

  banks: [
    /* ---- OSC 1 ---- */
    { label: "Osc 1", knobs: [
        wavesel("osc1_wave", "Wave", OSC1_WAVES, OSC1_SHAPES),
        bip("osc1_tune", "Tune"), bip("osc1_fine", "Fine"),
        uni("osc1_phase", "Phse"), uni("osc1_pw", "PW"), uni("osc1_vol", "Lvl")] },

    /* ---- OSC 2 ---- */
    { label: "Osc 2", knobs: [
        wavesel("osc2_wave", "Wave", OSC2_WAVES, OSC2_SHAPES),
        bip("osc2_tune", "Tune"), bip("osc2_fine", "Fine"),
        uni("osc2_phase", "Phse"), uni("osc2_fm", "FM"), uni("osc2_vol", "Lvl")] },

    /* ---- MASTER ---- */
    { label: "Master", knobs: [
        uni("osc3_vol", "Sub"), uni("volume", "Vol"), uni("highpass", "HP"),
        uni("vintage", "Nois"), uni("detune", "Detn"), uni("ringmod", "Ring"),
        tog("osc_sync", "Sync"), bip("osc_tune", "MTun")] },

    /* ---- FILTER (+ response curve) ---- */
    { label: "Filter", knobs: [
        enumc("filter_type", "Type", FILT, FILT_SQ),
        uni("cutoff", "Cut"), uni("resonance", "Res"), uni("keyfollow", "Key"),
        uni("filter_env", "Cont"), uni("filter_drive", "Driv"), blank(), blank()],
      filterViz: { cell: 6, cutoffKey: "cutoff", resoKey: "resonance",
                   mode: { key: "filter_type", modes: FILT_MODES } } },

    /* ---- Filter Env ---- */
    { label: "Filter Env", env: true, knobs: [
        fader("fenv_a", "A"), fader("fenv_d", "D"), fader("fenv_s", "S"), fader("fenv_r", "R")] },

    /* ---- Amp Env (+ Free/Env3, as TAL groups them) ---- */
    { label: "Amp Env", env: true, knobs: [
        fader("aenv_a", "A"), fader("aenv_d", "D"), fader("aenv_s", "S"), fader("aenv_r", "R"),
        uni("free_a", "E3A"), uni("free_d", "E3D"), bip("free_amt", "E3Amt"),
        enumc("free_dest", "E3Ds", FDST, FDST_SQ)] },

    /* ---- LFO 1 ---- */
    { label: "LFO 1", knobs: [
        wavesel("lfo1_wave", "Wave", LFO_WAVES, LFO_SHAPES),
        uni("lfo1_rate", "Rate"), uni("lfo1_amount", "Amt"), uni("lfo1_phase", "Phse"),
        enumc("lfo1_dest", "Dest", LDST1, LDST1_SQ),
        tog("lfo1_sync", "Sync"), tog("lfo1_keytrig", "Trig")] },

    /* ---- LFO 2 ---- */
    { label: "LFO 2", knobs: [
        wavesel("lfo2_wave", "Wave", LFO_WAVES, LFO_SHAPES),
        uni("lfo2_rate", "Rate"), uni("lfo2_amount", "Amt"), uni("lfo2_phase", "Phse"),
        enumc("lfo2_dest", "Dest", LDST2, LDST2_SQ),
        tog("lfo2_sync", "Sync"), tog("lfo2_keytrig", "Trig")] },

    /* ---- Voicing / Velocity / Wheel ---- */
    { label: "Voice / Vel", knobs: [
        count("voices", "Vcs", 1, 6), uni("portamento", "Port"),
        enumc("porta_mode", "PMde", PMODE),
        uni("vel_vol", "VVol"), uni("vel_env", "VEnv"), uni("vel_cut", "VCut"),
        uni("pw_cutoff", "WCut"), uni("pw_pitch", "Bend")] },

    /* ---- Chorus / Crush / Reverb ---- */
    { label: "Chorus / Reverb", knobs: [
        tog("chorus1", "Ch1"), tog("chorus2", "Ch2"), uni("bitcrush", "Crsh"),
        uni("reverb_wet", "RWet"), uni("reverb_decay", "RSiz"), uni("reverb_pre", "RPre"),
        uni("reverb_hi", "RHi"), uni("reverb_lo", "RLo")] },

    /* ---- Delay ---- */
    { label: "Delay", knobs: [
        uni("delay_wet", "Wet"), uni("delay_time", "Time"), uni("delay_fb", "Fbk"),
        tog("delay_sync", "Sync"), tog("delay_fac_l", "2xL"), tog("delay_fac_r", "2xR"),
        uni("delay_hi", "HiCt"), uni("delay_lo", "LoCt")] },
  ],

  sections: [
    { name: "OSC 1", bank: 0 }, { name: "OSC 2", bank: 1 }, { name: "MASTER", bank: 2 },
    { name: "FILTER", bank: 3 }, { name: "FILT ENV", bank: 4 }, { name: "AMP ENV", bank: 5 },
    { name: "LFO 1", bank: 6 }, { name: "LFO 2", bank: 7 }, { name: "VOICE", bank: 8 },
    { name: "REVERB", bank: 9 }, { name: "DELAY", bank: 10 },
  ],

  icons: ["sawpulse","sawpulse","global","lp","envf","enva","sine","sine","bend","pan","routes"],

  /* Off-device defaults only (previewer/tests); on device every read is live. */
  defaults: {
    osc1_wave: 0, osc1_tune: 50, osc1_fine: 50, osc1_phase: 0, osc1_pw: 50, osc1_vol: 80,
    osc2_wave: 0, osc2_tune: 50, osc2_fine: 50, osc2_phase: 0, osc2_fm: 0, osc2_vol: 0,
    osc3_vol: 0, volume: 50, highpass: 0, vintage: 0, detune: 20, ringmod: 0, osc_sync: 0, osc_tune: 50,
    filter_type: 0, cutoff: 60, resonance: 12, keyfollow: 30, filter_env: 35, filter_drive: 0,
    fenv_a: 0, fenv_d: 45, fenv_s: 30, fenv_r: 30,
    aenv_a: 0, aenv_d: 50, aenv_s: 85, aenv_r: 28, free_a: 0, free_d: 0, free_amt: 50, free_dest: 0,
    lfo1_wave: 0, lfo1_rate: 30, lfo1_amount: 0, lfo1_phase: 0, lfo1_dest: 0, lfo1_sync: 0, lfo1_keytrig: 0,
    lfo2_wave: 0, lfo2_rate: 30, lfo2_amount: 0, lfo2_phase: 0, lfo2_dest: 0, lfo2_sync: 0, lfo2_keytrig: 0,
    voices: 6, portamento: 0, porta_mode: 0, vel_vol: 0, vel_env: 0, vel_cut: 0, pw_cutoff: 0, pw_pitch: 20,
    chorus1: 0, chorus2: 0, bitcrush: 0, reverb_wet: 0, reverb_decay: 0, reverb_pre: 0, reverb_hi: 100, reverb_lo: 0,
    delay_wet: 0, delay_time: 30, delay_fb: 0, delay_sync: 0, delay_fac_l: 0, delay_fac_r: 0, delay_hi: 100, delay_lo: 0,
  },

  testExports: { FILT, LDST1, LDST2, FDST, PMODE },
};


/* ==== kit engine ==== */

/* ==== schwung-canvaskit core: engine ====
 * Everything downstream of the module CONFIG: bank model aliases, state,
 * movy-style widgets (arc knobs / bar toggles / enum + value squares / ADSR
 * graphic — adapted from schwung-movy src/renderer/*.ts, MIT (c) 2026
 * megadake), header chrome + icon set, SHIFT section picker, enum overlay,
 * input handling, param cache, and the bank_editor overlay object. */

/* ---- module config aliases ---- */
const BANKS = CONFIG.banks;
const JUMP_SECTIONS = CONFIG.sections;
const BANK_ICONS = CONFIG.icons || [];
const DEFAULTS = CONFIG.defaults || {};
/* Detents per picker step while SHIFT-scrolling (1 = one section per click). */
const NAV_SENS = CONFIG.navSens || 1;

/* Which section the current bank falls under (the last target <= bankIdx). */
function activeSection(bankIdx) {
  let idx = 0;
  for (let i = 0; i < JUMP_SECTIONS.length; i++) if (JUMP_SECTIONS[i].bank <= bankIdx) idx = i;
  return idx;
}

/* ---- dynamic cells + step-editor plumbing ----
 * bank.dynamicCells(ctx) -> cells[]  — type-dependent pages (FX banks whose
 *   knobs relabel by the armed type; dest cells with live route names).
 * bank.steps = { csv, sel, lvl, count, max?, active?(ctx), stepMs?(ctx) }
 *   — an echidna-style step-sequencer editor reached by jogging RIGHT from
 *   the bank (jog LEFT backs out). Engine contract: `csv` getParam returns
 *   comma-separated levels; writes go `sel` (step index) then `lvl` (value);
 *   `count` is the step-count param key (or a number). */

function stepsMax(bank) { return (bank.steps && bank.steps.max) || KIT_PARAM_MAX; }
function stepsCenter(bank) { return Math.round(stepsMax(bank) / 2); }

function stepCount(ctx, bank) {
  const c = bank.steps.count;
  if (typeof c === "number") return c;
  const v = parseInt(ctx.getParam(c) || "8", 10);
  return isNaN(v) ? 8 : Math.max(1, Math.min(32, v));
}

function stepCells(bank, page) {
  const a = [];
  for (let k = 0; k < 8; k++) {
    a.push({ label: String(page * 8 + k + 1), kind: "steplvl", min: 0, max: stepsMax(bank), stepIdx: page * 8 + k });
  }
  return a;
}

function subPageCount(ctx, bank) {
  if (!bank.steps) return 0;
  if (bank.steps.active && !bank.steps.active(ctx)) return 0;
  return Math.ceil(stepCount(ctx, bank) / 8);
}

/* The active bank's cells for the current sub-page. dynamicCells receives
 * (ctx, s) — s for banks whose layout depends on local UI state (a route
 * cursor picking which param a cell edits); ctx-only configs ignore it. */
function cellsFor(ctx, bank, sub, s) {
  if (bank.steps && sub >= 1) return stepCells(bank, sub - 1);
  return bank.dynamicCells ? bank.dynamicCells(ctx, s) : bank.knobs;
}

/* Header text: bank.header(ctx, s) makes it live ("FX 1: Drive"). */
function headerFor(ctx, bank, s) {
  return bank.header ? String(bank.header(ctx, s)) : bank.label;
}

/* What the header bar shows this frame: normally the bank header
 * (left-aligned); while a knob is touched/turned, the touched cell's FULL
 * param name (cell.name, falling back to its short label), centered — the
 * label strip below swaps to the VALUE, so the header carries the name. */
function headerTextFor(ctx, bank, s, cells) {
  const t = s.lastKnob >= 0 && cells ? cells[s.lastKnob] : null;
  if (t && t.kind !== "blank") return { text: String(t.name || t.label), centered: true };
  return { text: headerFor(ctx, bank, s), centered: false };
}

/* Batch-read the step levels from the engine's CSV getter. One parse per
 * draw; missing engine data -> all-center so the editor draws pre-wire. */
function stepVals(ctx, bank) {
  const center = stepsCenter(bank);
  const raw = ctx.getParam(bank.steps.csv);
  const a = [];
  if (!raw) { for (let i = 0; i < 32; i++) a.push(center); return a; }
  const parts = String(raw).split(",");
  for (let i = 0; i < 32; i++) { const v = parseInt(parts[i], 10); a.push(isNaN(v) ? center : v); }
  return a;
}

/* Which step the playhead is on right now. Default 125ms/step (~120bpm
 * 1/16ths); banks can supply steps.stepMs(ctx) for the real rate. */
function stepPlayhead(ctx, bank, count) {
  const ms = bank.steps.stepMs ? bank.steps.stepMs(ctx) : 125;
  return Math.floor(nowMs() / Math.max(1, ms)) % Math.max(1, count);
}

/* ---- state / lifecycle ---- */

function readState(ctx) {
  const s = ctx.state;
  if (!s.init) {
    s.init = true;
    let v = parseInt(ctx.getValue() || "0", 10);
    if (isNaN(v)) v = 0;
    s.bank = clampBank(v, BANKS.length);
    s.accum = [0, 0, 0, 0, 0, 0, 0, 0];
    s.lastKnob = -1;
    s.shift = false;       // SHIFT fallback state (CC 49) for off-device runs
    s.jogAccum = 0;        // shift+jog detent accumulator
    s.sub = 0;             // step-editor sub-page (0 = the bank's config page)
    s.stepSelKey = null;   // step-editor cursor (bank:idx) written to the engine
    s.stepVal = 0;         // tracked value of the step being edited
  }
  return s;
}

/* ---- value formatting ---- */

/* 8 rows: 1px pad + 6px header-font glyphs + 1px pad. */
const HDR_H = 8;

/* A cell's current value in its native-int domain. Hooks (all optional):
 *   cell.get(ctx) -> int     — bypass the param system entirely (local UI
 *                              cursors reading ctx.state, computed values).
 *   cell.parse(wire) -> int  — decode a non-int wire format (float-string
 *                              engines, enums whose get_param returns the
 *                              option LABEL). NaN falls back like parseInt. */
function getRaw(ctx, cell) {
  if (cell.get) return cell.get(ctx);
  const fallback = cell.dflt != null ? cell.dflt : cell.min;
  const raw = ctx.getParam(cell.key);
  if (raw == null || raw === "") return fallback;
  const v = cell.parse ? cell.parse(String(raw)) : parseInt(raw, 10);
  return (typeof v === "number" && !isNaN(v)) ? v : fallback;
}

/* Trim text from the end until it fits maxW px (measured in the live font). */
function fitText(ctx, text, maxW) {
  if (maxW <= 0) return "";
  let t = String(text);
  while (t.length > 0 && ctx.measureText(t) > maxW) t = t.slice(0, -1);
  return t;
}

/* Resolve {text, bar/centerBar/fader} for a cell. bar/fader are null unless
 * that cell's kind uses them (each is a 0..1 fill fraction); centerBar is a
 * -1..1 signed fraction for the center-detent kinds. */
function formatCell(ctx, cell) {
  const f = formatCellBase(ctx, cell);
  // cell.text(ctx) overrides the display STRING only (bars keep kind logic):
  // raw engine strings ("1 Init" preset names), rescaled readouts ("1.00").
  if (cell.text) f.text = String(cell.text(ctx));
  return f;
}

function formatCellBase(ctx, cell) {
  const raw = getRaw(ctx, cell);
  // Every option-backed kind resolves its LABEL (not the raw index): plain
  // enums plus the length square, xbox, action and direction cells.
  if (cell.options && (cell.kind === "enum" || cell.kind === "len" ||
      cell.kind === "xbox" || cell.kind === "action" || cell.kind === "dir")) {
    const idx = raw - cell.min;
    const name = cell.options[idx] || ("#" + raw);
    return { text: name, bar: null, fader: null };
  }
  if (cell.kind === "bipolar") {
    const center = cell.dflt != null ? cell.dflt : Math.round((cell.min + cell.max) / 2);
    const signed = raw - center;
    const halfR = Math.max(1, Math.max(cell.max - center, center - cell.min));
    return { text: (signed > 0 ? "+" : "") + signed, bar: null, fader: null, centerBar: signed / halfR };
  }
  if (cell.kind === "octave") {
    return { text: (raw > 0 ? "+" : "") + raw, bar: null, fader: null };
  }
  if (cell.kind === "count") {
    return { text: String(raw), bar: null, fader: null };
  }
  const frac = Math.max(0, Math.min(1, (raw - cell.min) / (cell.max - cell.min)));
  if (cell.kind === "fader") return { text: String(raw), bar: null, fader: frac };
  return { text: String(raw), bar: frac, fader: null }; // unipolar
}

/* ---- icon set (drawn in the picker rows; header stays label-only) ----
 * Built-ins below; a config can add its own via CONFIG.customIcons:
 *   { myicon: { w: 12, draw(ctx, x, y, fg) { ... } } }
 * and reference "myicon" in CONFIG.icons. */

const ICON_W = { sawpulse: 12, pulse: 8, lp: 11, hp: 11, envf: 17, enva: 17, env: 12, sine: 13, routes: 12, bend: 12, random: 11, pan: 13, global: 7 };

function iconW(icon) {
  const c = CONFIG.customIcons && CONFIG.customIcons[icon];
  return c ? c.w : (ICON_W[icon] || 0);
}

function plotLine(ctx, x1, y1, x2, y2, fg) {
  const dx = x2 - x1, dy = y2 - y1;
  const steps = Math.max(1, Math.round(Math.max(Math.abs(dx), Math.abs(dy))));
  for (let s = 0; s <= steps; s++) {
    const t = s / steps;
    ctx.setPixel(Math.round(x1 + dx * t), Math.round(y1 + dy * t), fg);
  }
}

function drawBankIcon(ctx, x, y, icon, fg) {
  fg = fg ? 1 : 0;
  const custom = CONFIG.customIcons && CONFIG.customIcons[icon];
  if (custom) return custom.draw(ctx, x, y, fg);
  if (icon === "sawpulse") {
    // a saw tooth next to a pulse wave
    plotLine(ctx, x, y + 6, x + 4, y, fg); plotLine(ctx, x + 4, y, x + 4, y + 6, fg);
    plotLine(ctx, x + 6, y + 6, x + 6, y, fg);
    ctx.fillRect(x + 6, y, 3, 1, fg);
    plotLine(ctx, x + 8, y, x + 8, y + 6, fg);
    ctx.fillRect(x + 8, y + 6, 3, 1, fg);
    plotLine(ctx, x + 10, y + 6, x + 10, y, fg);
  } else if (icon === "pulse") {
    // single pulse bracket (PW)
    plotLine(ctx, x, y + 6, x, y, fg);
    ctx.fillRect(x, y, 4, 1, fg);
    plotLine(ctx, x + 3, y, x + 3, y + 6, fg);
    ctx.fillRect(x + 3, y + 6, 4, 1, fg);
    plotLine(ctx, x + 6, y + 6, x + 6, y, fg);
  } else if (icon === "lp") {
    ctx.fillRect(x, y + 1, 6, 1, fg); plotLine(ctx, x + 5, y + 1, x + 10, y + 6, fg);
  } else if (icon === "hp") {
    plotLine(ctx, x, y + 6, x + 5, y + 1, fg); ctx.fillRect(x + 5, y + 1, 6, 1, fg);
  } else if (icon === "env") {
    // plain ADSR shape (no letter tag)
    plotLine(ctx, x, y + 6, x + 2, y, fg); plotLine(ctx, x + 2, y, x + 5, y + 3, fg);
    ctx.fillRect(x + 5, y + 3, 3, 1, fg); plotLine(ctx, x + 8, y + 3, x + 11, y + 6, fg);
  } else if (icon === "envf" || icon === "enva") {
    // Env banks: an A (Amp) or F (Filter) tag to the left of the ADSR shape.
    ctx.print(x - 2, y + 1, icon === "enva" ? "A" : "F", fg);
    const ex = x + 5;
    plotLine(ctx, ex, y + 6, ex + 2, y, fg); plotLine(ctx, ex + 2, y, ex + 5, y + 3, fg);
    ctx.fillRect(ex + 5, y + 3, 3, 1, fg); plotLine(ctx, ex + 8, y + 3, ex + 11, y + 6, fg);
  } else if (icon === "sine") {
    // continuous sine (LFO)
    let py = y + 3;
    for (let i = 1; i <= 12; i++) {
      const cy = y + 3 - Math.round(2.5 * Math.sin((i / 12) * Math.PI * 4));
      plotLine(ctx, x + i - 1, py, x + i, cy, fg);
      py = cy;
    }
  } else if (icon === "routes") {
    // filled right-pointing arrow (mod/LFO destinations)
    ctx.fillRect(x, y + 2, 6, 3, fg);
    for (let c = 0; c <= 6; c++) {
      const hh = 3 - Math.floor(c / 2);
      ctx.fillRect(x + 5 + c, y + 3 - hh, 1, hh * 2 + 1, fg);
    }
  } else if (icon === "bend") {
    // pitch mod: a ramp bending up with an arrowhead
    plotLine(ctx, x, y + 6, x + 8, y + 1, fg);
    plotLine(ctx, x + 5, y, x + 8, y + 1, fg);
    plotLine(ctx, x + 8, y + 1, x + 7, y + 4, fg);
  } else if (icon === "random") {
    // scattered dots (per-voice variation / drift)
    const dots = [[0, 4], [1, 2], [3, 5], [4, 1], [6, 4], [7, 2], [9, 5], [10, 3]];
    for (const [dx, dy] of dots) ctx.setPixel(x + dx, y + dy, fg);
  } else if (icon === "pan") {
    // stereo pan: center bar with arrows pointing left + right
    ctx.fillRect(x + 6, y + 1, 1, 5, fg);
    plotLine(ctx, x + 4, y + 3, x + 1, y + 3, fg);
    ctx.setPixel(x + 2, y + 2, fg); ctx.setPixel(x + 2, y + 4, fg);
    plotLine(ctx, x + 8, y + 3, x + 11, y + 3, fg);
    ctx.setPixel(x + 10, y + 2, fg); ctx.setPixel(x + 10, y + 4, fg);
  } else if (icon === "global") {
    ctx.fillRect(x + 2, y + 2, 3, 3, fg);
    ctx.setPixel(x + 3, y, fg); ctx.setPixel(x + 3, y + 6, fg); ctx.setPixel(x, y + 3, fg); ctx.setPixel(x + 6, y + 3, fg);
    ctx.setPixel(x + 1, y + 1, fg); ctx.setPixel(x + 5, y + 1, fg); ctx.setPixel(x + 1, y + 5, fg); ctx.setPixel(x + 5, y + 5, fg);
  }
}

/* Header bar: normally plain white-on-black — bank label, left-aligned
 * (icons live on the picker rows) — with the page indicator below it.
 * While a knob is touched/turned (`swap`) it INVERTS to a filled bar with
 * the param name in black, centered — the state change is the touch
 * feedback. */
/* Header text is ALL CAPS (Josh's call — the chunky font reads best that
 * way); trims from the end until it fits. */
function fitHdr(text, maxW) {
  let t = String(text).toUpperCase();
  while (t.length > 0 && hdrWidth(t) > maxW) t = t.slice(0, -1);
  return t;
}

function drawChrome(ctx, headerLabel, s, swap) {
  const t = fitHdr(headerLabel, ctx.width - 4);
  if (swap) {
    // filled bar rows 0-7 (text 1-6), param name centered in black —
    // no page-indicator bar while adjusting.
    ctx.fillRect(0, 0, ctx.width, HDR_H, 1);
    hdrPrint(ctx, Math.max(2, Math.round((ctx.width - hdrWidth(t)) / 2)), 1, t, 0);
    return;
  }
  hdrPrint(ctx, 2, 1, t, 1);
  // Page-indicator bar on row 9, resting state only: one segment per bank
  // split by 1px dividers; the ACTIVE bank's segment FLASHES between solid
  // and dotted (every other px — movy's step-page style) at ~1.3Hz off the
  // wall/tempo clock; the rest stay solid.
  const barY = HDR_H + 1;
  const n = BANKS.length;
  if (n <= 1) {
    ctx.fillRect(0, barY, ctx.width, 1, 1);
  } else {
    const blinkOn = Math.floor(nowMs() / 375) % 2 === 0;
    // Spread the rounding remainder across the first segments (an extra px
    // each) instead of dumping it all into the last one, so every segment
    // reads the same width and the page count is legible.
    const usable = ctx.width - (n - 1);
    const base = Math.floor(usable / n), rem = usable % n;
    for (let b = 0, sx = 0; b < n; b++) {
      const sw = base + (b < rem ? 1 : 0);
      if (b !== s.bank || blinkOn) {
        ctx.fillRect(sx, barY, sw, 1, 1);
      } else {
        for (let x = sx; x < sx + sw; x += 2) ctx.setPixel(x, barY, 1);
      }
      sx += sw + 1;
    }
  }
}

/* Section-picker overlay — shown ONLY while SHIFT is held. One row per
 * SECTION (coarse jumps; plain jog browses every bank overlay-free), each
 * carrying its section's icon right-aligned. Shift+jog moves the highlight;
 * releasing shift leaves you on that section's first bank. */
function drawBankPicker(ctx, s) {
  if (!shiftHeld(s)) return;
  const items = JUMP_SECTIONS;
  const active = activeSection(s.bank);
  const x = 4, y = 2, w = ctx.width - 8, h = ctx.height - 4;
  ctx.fillRect(x, y, w, h, 0);   // clear the screen beneath
  ctx.drawRect(x, y, w, h, 1);   // popup frame
  const rowH = 8, listY = y + 3, visible = 7;
  // Scroll so the active row stays in view (centered where possible).
  let top = active - Math.floor(visible / 2);
  top = Math.max(0, Math.min(Math.max(0, items.length - visible), top));
  for (let r = 0; r < visible; r++) {
    const i = top + r;
    if (i >= items.length) break;
    const ry = listY + r * rowH;
    const sel = i === active;
    if (sel) ctx.fillRect(x + 2, ry - 1, w - 6, rowH, 1);
    ctx.print(x + 4, ry, items[i].name, sel ? 0 : 1);
    const icon = BANK_ICONS[items[i].bank];
    if (icon) drawBankIcon(ctx, x + w - iconW(icon) - 7, ry, icon, sel ? 0 : 1);
  }
  // Right-edge scrollbar: track + a thumb sized/positioned to the window.
  const trackY = listY - 1, trackH = visible * rowH;
  const thumbH = Math.max(4, Math.round(trackH * visible / items.length));
  const denom = Math.max(1, items.length - visible);
  const thumbY = trackY + Math.round((trackH - thumbH) * top / denom);
  ctx.fillRect(x + w - 2, trackY, 1, trackH, 1);
  ctx.fillRect(x + w - 3, thumbY, 2, thumbH, 1);
}

/* ---- movy-style widget renderers ---- */

/* Layout: 8px header (6x6 pixel-font text) + blank rows + the indicator
 * bar, then two 16px widget rows each with its 7px label strip DIRECTLY
 * beneath (the knob circle is 15px in the 16px cell, so knobs keep a 1px
 * visual gap; squares sit flush):
 * hdr 0-7 (text 1-6) | blank 8 | bar 9 | gap 10-13 |
 * w0 14-29 | lbl0 30-36 | gap 37-40 | w1 41-56 | lbl1 57-63. */
const ROW0_Y = 14, LBL0_Y = 30, ROW1_Y = 41, LBL1_Y = 57;
const CELL_W = 32, KW = 20, KH = 16, LBL_H = 7;
/* Centred overlay box. The picker lives here; the turn-to-reveal value zoom
 * (davebox, not yet in the kit) shares the same footprint so the two read as
 * one control rather than two different pop-ups. */
const ZOOM_X = 32, ZOOM_Y = 14, ZOOM_W = 64, ZOOM_H = 48;

function drawCircleBorder(ctx, cx, cy, r) {
  let x = r, y = 0, err = 0;
  while (x >= y) {
    if (y === 0) {
      // Cardinal extremes tucked in by 1: the raw midpoint circle leaves a
      // single pixel poking out at the exact top/bottom/left/right; plotting
      // them at r-1 sits flush with the neighbouring rows/columns instead.
      ctx.setPixel(cx + x - 1, cy, 1); ctx.setPixel(cx - x + 1, cy, 1);
      ctx.setPixel(cx, cy + x - 1, 1); ctx.setPixel(cx, cy - x + 1, 1);
    } else {
      ctx.setPixel(cx + x, cy + y, 1); ctx.setPixel(cx + y, cy + x, 1);
      ctx.setPixel(cx - y, cy + x, 1); ctx.setPixel(cx - x, cy + y, 1);
      ctx.setPixel(cx - x, cy - y, 1); ctx.setPixel(cx - y, cy - x, 1);
      ctx.setPixel(cx + y, cy - x, 1); ctx.setPixel(cx + x, cy - y, 1);
    }
    y++;
    if (err <= 0) err += 2 * y + 1;
    if (err > 0) { x--; err -= 2 * x + 1; }
  }
}

/* Arc knob: circle + a pointer line sweeping 300 degrees (210 -> 510).
 * Bipolar cells get a 12-o'clock center tick inside the dial. */
function drawArcKnob(ctx, kx, ky, norm, bipolar) {
  const cx = kx + 10, cy = ky + 7, r = 7;
  drawCircleBorder(ctx, cx, cy, r);
  if (bipolar) ctx.fillRect(cx, cy - r + 1, 1, 2, 1);
  // Pointer stops at r-1 so it meets the tucked-in border, never past it.
  const rad = (210 + norm * 300) * Math.PI / 180;
  const ex = Math.round(cx + (r - 1) * Math.sin(rad));
  const ey = Math.round(cy - (r - 1) * Math.cos(rad));
  plotLine(ctx, cx, cy, ex, ey, 1);
}

/* Horizontal bar filling left->right — the movy binary widget (toggles). */
function drawHBar(ctx, kx, ky, norm) {
  ctx.fillRect(kx + 1, ky + 4, 18, 1, 1);
  ctx.fillRect(kx + 1, ky + 10, 18, 1, 1);
  ctx.fillRect(kx + 1, ky + 4, 1, 7, 1);
  ctx.fillRect(kx + 18, ky + 4, 1, 7, 1);
  const fillW = Math.round(norm * 16);
  if (fillW > 0) ctx.fillRect(kx + 2, ky + 5, fillW, 5, 1);
}

/* Vertical bar filling bottom->up — mix/level feel (env Vel cells). */
function drawVBar(ctx, kx, ky, norm) {
  ctx.fillRect(kx + 6, ky + 1, 8, 1, 1);
  ctx.fillRect(kx + 6, ky + 14, 8, 1, 1);
  ctx.fillRect(kx + 6, ky + 1, 1, 14, 1);
  ctx.fillRect(kx + 13, ky + 1, 1, 14, 1);
  const fillH = Math.round(norm * 12);
  if (fillH > 0) ctx.fillRect(kx + 7, ky + 2 + (12 - fillH), 6, fillH, 1);
}

/* Framed square with the enum value as up to two 3-char 5x3 lines
 * (or a single provided square label). */
function drawEnumSquare(ctx, kx, ky, text, sqText) {
  ctx.drawRect(kx, ky, KW, KH, 1);
  const lines = sqText != null ? [String(sqText), ""] : enumSquareLines(text);
  const inner = KW - 2;
  const totalH = lines[1].length > 0 ? 11 : 5;
  const startY = ky + 1 + Math.floor((KH - 2 - totalH) / 2);
  const w1 = pf3Width(lines[0]);
  pf3Print(ctx, kx + 1 + Math.floor((inner - w1) / 2), startY, lines[0], 1);
  if (lines[1].length > 0) {
    const w2 = pf3Width(lines[1]);
    pf3Print(ctx, kx + 1 + Math.floor((inner - w2) / 2), startY + 6, lines[1], 1);
  }
}

/* Big numeric read-out (movy's 'preset' render style): the value in the 13pt
 * font, NO frame, centered across the FULL 32px cell — it spills into the side
 * margins the 20px widget box leaves, which is what buys the extra characters.
 * `cellX` is the cell's left edge, not the widget box's. Picks normal spacing,
 * else condensed, else drops to the label font so it always fits. */
/* Framed box with a big diagonal cross — DRAWN, not a font glyph (movy
 * drawXBox). movy's "this modulation target is None": an empty-slot
 * affordance that reads as "nothing routed here" at a glance. */
function drawXBox(ctx, kx, ky) {
  ctx.drawRect(kx, ky, KW, KH, 1);
  const a = 3, b = KW - 1 - 3;          // inset the cross from the frame
  plotLine(ctx, kx + a, ky + a, kx + b, ky + KH - 1 - a, 1);
  plotLine(ctx, kx + b, ky + a, kx + a, ky + KH - 1 - a, 1);
}

/* Musical length as a STACKED FRACTION — frameless, centred across the FULL
 * 32px cell: numerator, rule, denominator in the 6x6 header font. The sibling
 * of drawBigNum for values that are true n/m fractions, and the answer for
 * labels too long for the big read-out even condensed ("1/64d" = 36px).
 *
 * A triplet/dotted suffix modifies the WHOLE fraction, not the denominator,
 * so the rule spans only numerator/denominator and the suffix sits to its
 * right on the denominator's line. Stacking it INTO the denominator reads as
 * "one over sixteen-d"; centring it on the rule's axis leaves it floating
 * beside the value. Both were tried on hardware and rejected.
 *
 * Vertical budget is the whole story: 6 + rule + 6 = 13px of ink in a 16px
 * row, so the parts sit at ky+0 and ky+9 with the rule at ky+7 — the only
 * arrangement leaving clear space on both sides of the rule. movy's BOXED
 * 5x3 drawLengthSquare (which this replaces) failed here: its frame stole
 * 2px a side and its parts touched the rule outright — numerator at ky+2,
 * rule at ky+7, denominator at ky+8, zero gap either side. Don't re-port it. */
const SFX_GAP = 2;
function drawFracStack(ctx, cellX, ky, text) {
  const t = String(text);
  const m = t.match(/^(\d+)\/(\d+)([A-Za-z]*)$/);
  /* Not an n/m fraction ("1bar", "--"): these sets are mixed, so fall back to
   * the big read-out rather than a small centred string — the two forms then
   * read as one hierarchy instead of two different widgets. */
  if (!m) return drawBigNum(ctx, cellX, ky, t);
  const num = m[1], den = m[2], sfx = m[3];
  const nw = hdrWidth(num), dw = hdrWidth(den);
  const fracW = Math.max(nw, dw) + 2;       // rule overhangs the wider part
  const sw = sfx ? hdrWidth(sfx) : 0;
  const total = fracW + (sfx ? SFX_GAP + sw : 0);
  const left = cellX + Math.round((CELL_W - total) / 2);
  hdrPrint(ctx, left + Math.round((fracW - nw) / 2), ky, num, 1);
  ctx.fillRect(left, ky + 7, fracW, 1, 1);
  hdrPrint(ctx, left + Math.round((fracW - dw) / 2), ky + 9, den, 1);
  if (sfx) hdrPrint(ctx, left + fracW + SFX_GAP, ky + 9, sfx, 1);
}

/* One-shot / relative action square (davebox). Resting it shows "< >" —
 * "turn either way" — because the control has no absolute value to display;
 * while its knob is touched the live VALUE takes over the box, mirroring the
 * label<->value swap. `oneWay` (destructive actions) stays "< >" even when
 * touched: there is genuinely nothing to show. */
function drawActionSquare(ctx, kx, ky, text, oneWay, touched) {
  ctx.drawRect(kx, ky, KW, KH, 1);
  const t = (touched && !oneWay) ? String(text) : "< >";
  const w = pf3Width(t);
  pf3Print(ctx, kx + 1 + Math.floor((KW - 2 - w) / 2), ky + 1 + Math.floor((KH - 2 - 5) / 2), t, 1);
}

/* Playback-direction square (davebox): real arrows rather than an abbreviation
 * — 0 forward, 1 backward, 2 ping-pong out, 3 ping-pong in. */
function drawDirSquare(ctx, kx, ky, mode) {
  ctx.drawRect(kx, ky, KW, KH, 1);
  const cy = ky + Math.floor(KH / 2);
  const tri = (x, dir) => {              // 4-col solid triangle; dir 1 = right
    for (let c = 0; c < 4; c++) {
      const h = dir > 0 ? 7 - 2 * c : 1 + 2 * c;
      ctx.fillRect(x + c, cy - (h >> 1), 1, h, 1);
    }
  };
  const mid = kx + Math.floor(KW / 2);
  if (mode === 0) tri(mid - 2, 1);
  else if (mode === 1) tri(mid - 2, -1);
  else if (mode === 2) { tri(mid - 7, -1); tri(mid + 3, 1); }   // outward
  else { tri(mid - 7, 1); tri(mid + 3, -1); }                   // inward
}

function drawBigNum(ctx, cellX, ky, text) {
  const t = String(text);
  const fit = bigFit(t, CELL_W);
  if (fit) {
    bigPrint(ctx, cellX + Math.round((CELL_W - fit.w) / 2),
             ky + Math.floor((KH - BIG_H) / 2), t, 1, fit.cond);
  } else {
    const sw = mvWidth(t);
    mvPrint(ctx, cellX + Math.round((CELL_W - sw) / 2),
            ky + Math.floor((KH - 5) / 2), t, 1);
  }
}

function normOf(ctx, cell) {
  const frac = (getRaw(ctx, cell) - cell.min) / (cell.max - cell.min);
  return Math.max(0, Math.min(1, frac));
}

/* Which movy widget a cell kind renders as. */
function widgetFor(cell) {
  if (cell.kind === "blank") return "blank";
  if (cell.kind === "waveenum") return "wave";
  if (cell.kind === "enum") return cell.options.length <= 2 ? "hbar" : "enumsq";
  if (cell.kind === "octave" || cell.kind === "count") return "valsq";
  if (cell.kind === "xbox") return "xbox";
  if (cell.kind === "len") return "lensq";
  if (cell.kind === "action") return "action";
  if (cell.kind === "dir") return "dirsq";
  if (cell.kind === "bipolar") return "arcbip";
  if (cell.kind === "fader") return "vbar";
  return "arc"; // unipolar
}

function drawWidget(ctx, col, rowY, cell, touched) {
  const kx = col * CELL_W + Math.floor((CELL_W - KW) / 2);
  const style = widgetFor(cell);
  if (style === "blank") return;
  if (style === "wave") return drawWaveBox(ctx, kx, rowY, cell.shapes[getRaw(ctx, cell) - cell.min] || "sine");
  if (style === "hbar") return drawHBar(ctx, kx, rowY, normOf(ctx, cell));
  if (style === "vbar") return drawVBar(ctx, kx, rowY, normOf(ctx, cell));
  // cell.sqText(ctx): dynamic single-line square label (beats the static
  // per-option cell.sq array; e.g. "1234" for a reorder permutation).
  if (style === "enumsq") return drawEnumSquare(ctx, kx, rowY, formatCell(ctx, cell).text, cell.sqText ? cell.sqText(ctx) : (cell.sq ? cell.sq[getRaw(ctx, cell) - cell.min] : null));
  // valsq = a numeric read-out; it is drawn frameless across the whole cell,
  // so it takes the CELL origin, not the widget box's kx.
  if (style === "valsq") return drawBigNum(ctx, col * CELL_W, rowY, cell.sqText ? String(cell.sqText(ctx)) : formatCell(ctx, cell).text);
  if (style === "xbox") return drawXBox(ctx, kx, rowY);
  if (style === "lensq") return drawFracStack(ctx, col * CELL_W, rowY, formatCell(ctx, cell).text);
  if (style === "action") return drawActionSquare(ctx, kx, rowY, formatCell(ctx, cell).text, !!cell.oneWay, !!touched);
  if (style === "dirsq") return drawDirSquare(ctx, kx, rowY, getRaw(ctx, cell) - cell.min);
  drawArcKnob(ctx, kx, rowY, normOf(ctx, cell), style === "arcbip");
}

/* Label strip cell: the param NAME normally; while that knob is touched the
 * cell inverts and shows the live VALUE instead (movy's signature swap).
 * Rendered in the movy proportional font (mvPrint), like movy's own labels. */
function drawLabelCell(ctx, col, lblY, cell, touched) {
  let text = String(touched ? formatCell(ctx, cell).text : cell.label);
  while (text.length > 0 && mvWidth(text) > CELL_W - 2) text = text.slice(0, -1);
  const tw = mvWidth(text);
  const tx = Math.round(col * CELL_W + CELL_W / 2 - tw / 2);
  if (touched) {
    ctx.fillRect(col * CELL_W, lblY, CELL_W, LBL_H, 1);
    mvPrint(ctx, tx, lblY + 1, text, 0);
  } else {
    mvPrint(ctx, tx, lblY + 1, text, 1);
  }
}

function dottedV(ctx, x, y0, y1) {
  const lo = Math.min(y0, y1), hi = Math.max(y0, y1);
  for (let y = lo; y <= hi; y += 2) ctx.setPixel(x, y, 1);
}

function dottedH(ctx, x0, x1, y) {
  for (let x = x0; x <= x1; x += 2) ctx.setPixel(x, y, 1);
}

/* Envelope graphic in place of its knob widgets (movy envelope.ts). ONE
 * path for every width: the geometry is derived from the cells the envelope
 * owns (startCol..+cellCount-1), never from the 128px screen, so a 2-cell AD
 * and a 4-cell ADSR are the same code at different spans. Cells the graphic
 * does not cover keep their knob widgets. Each stage drives one vertex;
 * sustain is always a LEVEL, never a time.
 *
 * Stage fractions are movy's hand-tuned full-line values re-expressed as
 * fractions of the span (A .21, D .194, gate-off .694, R .266 — at a 4-cell
 * span those reproduce the original 26/24/88/33 pixel values). With fewer
 * time stages each one gets a roomier share, so a 2-cell envelope still
 * reads at its width instead of huddling at the left edge. */
function drawEnvelopeRow(ctx, rowY, cells, env) {
  const e = envSpec(env);
  const roles = e.roles;
  const has = (r) => roles.indexOf(r) >= 0;

  const leftX = e.startCol * CELL_W + 2;
  const rightX = (e.startCol + e.cellCount) * CELL_W - 2;
  const span = rightX - leftX;
  const baseY = rowY + KH - 2, topY = rowY + 1;
  const usableH = baseY - topY;

  // One value per stage, read from the cell at that stage's column position.
  const val = {};
  for (let k = 0; k < roles.length; k++) {
    const cell = cells[e.startCol + k];
    val[roles[k]] = cell ? normOf(ctx, cell) : 0;
  }

  // Widen the per-stage share when there are fewer time stages to spend it on.
  const timeStages = (has("a") ? 1 : 0) + (has("d") ? 1 : 0) + (has("r") ? 1 : 0);
  const k = timeStages >= 3 ? 1 : (timeStages === 2 ? 1.7 : 2.2);
  const GAP = Math.max(2, Math.round(span * 0.032));
  const A_F = 0.21 * k, D_F = 0.194 * k, R_F = 0.266 * k;
  const gateX = leftX + Math.round(span * 0.694);   // note-off reference

  const susY = has("s") ? baseY - Math.round(val["s"] * usableH) : baseY;
  const pts = [[leftX, baseY]];

  const peakX = Math.min(rightX - 2, leftX + Math.round(val["a"] * span * A_F));
  pts.push([peakX, topY]);                                   // attack rise
  let cur = peakX;
  if (has("d")) {                                            // decay to sustain (or base)
    cur = Math.min(rightX - 2, cur + GAP + Math.round(val["d"] * span * D_F));
    if (has("s") && has("r") && cur > gateX - 2) cur = gateX - 2;
    pts.push([cur, susY]);
  } else if (has("s")) {                                     // ASR: straight drop to level
    pts.push([cur, susY]);
  }
  let plateauEnd = cur;
  if (has("s")) {                                            // hold the plateau
    plateauEnd = has("r") ? gateX : rightX;
    if (plateauEnd > cur) { pts.push([plateauEnd, susY]); cur = plateauEnd; }
  }
  if (has("r")) {                                            // release to base
    const endX = Math.min(rightX, cur + GAP + Math.round(val["r"] * span * R_F));
    pts.push([endX, baseY]);
  }

  for (let i = 0; i < pts.length - 1; i++)
    plotLine(ctx, pts[i][0], pts[i][1], pts[i + 1][0], pts[i + 1][1], 1);
  // Dotted verticals highlight the plateau timing (the two middle corners).
  if (has("s")) {
    if (has("d")) dottedV(ctx, pts[2][0], susY, baseY);
    if (has("r")) dottedV(ctx, plateauEnd, susY, baseY);
  }
  // Bold vertex dots, nudged so the 2x2 marker straddles the vertex.
  for (const p of pts)
    ctx.fillRect(Math.min(ctx.width - 2, Math.max(0, p[0] - 1)), Math.max(rowY, p[1] - 1), 2, 2, 1);
}

/* `env: true` (the original contract) means a full-width ADSR at column 0.
 * An object declares a partial envelope: which cells it owns and which
 * stages are present ("adsr" | "ad" | "ar" | "asr" | "ads"). */
function envSpec(env) {
  if (!env || env === true) return { startCol: 0, cellCount: 4, roles: "adsr" };
  return {
    startCol: env.startCol || 0,
    cellCount: env.cellCount || 4,
    roles: env.roles || "adsr",
  };
}

/* Filter-response curve across two cells (cutoff + resonance) in place of
 * their knob widgets — the filter analogue of drawLfoWave/drawEnvelope
 * (movy filter-curve.ts, v0.23.0). The corner sits at the cutoff's
 * x-position; resonance sets the bump/dip magnitude. Labels below untouched.
 *
 * Config: filterViz: { cell, cutoffKey, resoKey, mode, slopeKey? } where
 * `mode` is a fixed mode id or { key, modes[] } mapping an enum value to one
 * of lp | hp | bp | notch | peak | ap | off. */
var FILT_PASS = 0.62;   // nominal pass-band gain (0..1 of the cell height)
/* Keep the corner this far inside the span so the roll-off stays visible even
 * fully open/closed — never a bare flat line. */
var FILT_EDGE = 0.10;
function filtBump(u, c, w) { return Math.exp(-Math.pow((u - c) * w, 2)); }

/* Gain 0..1 at horizontal position u (0..1 across the span). The lp/hp
 * roll-off is a quarter-ellipse: rounded at the corner, near-vertical where it
 * meets the floor, and 0 beyond — so the line ENDS at the bottom axis instead
 * of running on along it as a false floor. */
function filtGainAt(u, mode, c, r, steep) {
  const cx = FILT_EDGE + c * (1 - 2 * FILT_EDGE);
  const dropW = steep ? 0.07 : 0.11;
  const pk = r * (1 - FILT_PASS);
  const top = FILT_PASS + pk;
  const ellipse = (dist) => {
    const t = dist / dropW;
    return t >= 1 ? 0 : top * Math.sqrt(1 - t * t);
  };
  const shoulder = (dist) => FILT_PASS + pk * filtBump(dist, 0, 8);
  switch (mode) {
    case "lp": return u <= cx ? shoulder(cx - u) : ellipse(u - cx);
    case "hp": return u >= cx ? shoulder(u - cx) : ellipse(cx - u);
    case "bp": return Math.min(1, top * filtBump(u, cx, 5 + r * 4));
    case "notch": return Math.max(0, FILT_PASS - FILT_PASS * (0.5 + 0.5 * r) * filtBump(u, cx, 7));
    case "peak": return Math.min(1, FILT_PASS * 0.7 + (0.3 + 0.6 * r) * (1 - FILT_PASS * 0.7) * filtBump(u, cx, 6));
    default: return FILT_PASS;   // ap / off — flat
  }
}

function filtNorm(ctx, key) {
  const v = parseInt(ctx.getParam(key) || "0", 10);
  return Math.max(0, Math.min(1, (isNaN(v) ? 0 : v) / KIT_PARAM_MAX));
}

function drawFilterCurve(ctx, viz) {
  const col = viz.cell % 4;
  const rowY = viz.cell < 4 ? ROW0_Y : ROW1_Y;
  const x0 = col * CELL_W + 1;
  const spanW = 2 * CELL_W - 2;
  const topY = rowY + 1, botY = rowY + KH - 2;
  const h = botY - topY;

  let mode = typeof viz.mode === "string" ? viz.mode : "lp";
  if (viz.mode && viz.mode.key) {
    const i = parseInt(ctx.getParam(viz.mode.key) || "0", 10);
    mode = viz.mode.modes[isNaN(i) ? 0 : i] || "lp";
  }
  const cutoff = filtNorm(ctx, viz.cutoffKey);
  const reso = viz.resoKey ? filtNorm(ctx, viz.resoKey) : 0;
  const steep = viz.slopeKey
    ? (parseInt(ctx.getParam(viz.slopeKey) || "0", 10) || 0) === 1 : false;

  dottedH(ctx, x0, x0 + spanW, botY);          // frequency axis
  if (mode === "ap" || mode === "off") {
    dottedH(ctx, x0, x0 + spanW, Math.round(botY - FILT_PASS * h));
    return;
  }
  const yAt = (px) => {
    const g = filtGainAt((px - x0) / spanW, mode, cutoff, reso, steep);
    return Math.max(topY, Math.min(botY, Math.round(botY - g * h)));
  };
  // Skip runs lying flat on the bottom axis so the curve ends where it
  // reaches the floor rather than continuing along it.
  let prevX = x0, prevY = yAt(x0);
  for (let px = x0 + 1; px <= x0 + spanW; px++) {
    const y = yAt(px);
    if (prevY < botY || y < botY) plotLine(ctx, prevX, prevY, px, y, 1);
    prevX = px; prevY = y;
  }
}

/* Single-cell waveform box (wavesel cells): one cycle of the live shape
 * with a dotted center baseline, in place of an enum square. */
function drawWaveBox(ctx, kx, ky, shape) {
  const x0 = kx + 1, spanW = KW - 2;
  const topY = ky + 2, botY = ky + KH - 3;
  const baseY = Math.round((topY + botY) / 2);
  const amp = (botY - topY) / 2;
  for (let x = x0; x <= x0 + spanW; x += 2) ctx.setPixel(x, baseY, 1);
  let px = x0, py = Math.round(baseY - shapeSample(shape, 0) * amp);
  for (let i = 1; i <= spanW; i++) {
    const y = Math.round(baseY - shapeSample(shape, i / spanW) * amp);
    plotLine(ctx, px, py, x0 + i, y, 1);
    px = x0 + i; py = y;
  }
}

/* Two-cell LFO waveform span (movy lfo-wave.ts): replaces the widgets of
 * cells viz.cell and viz.cell+1 (same row) with two cycles of the live
 * shape. bank.lfoViz = { cell, shape: {key, shapes[]} | "sine",
 *   phaseKey?, bipolar? (default true), retrigKey? }.
 * Baseline: dotted center line when bipolar, bottom line when unipolar;
 * retrigger on -> bold dot at the start of the line. */
function drawLfoWave(ctx, viz, cells) {
  const col = viz.cell % 4;
  const rowY = viz.cell < 4 ? ROW0_Y : ROW1_Y;
  const x0 = col * CELL_W + 1;
  const spanW = 2 * CELL_W - 2;
  const topY = rowY + 1, botY = rowY + KH - 2;
  const bipolar = viz.bipolar !== false;
  const baseY = bipolar ? Math.round((topY + botY) / 2) : botY;
  const amp = bipolar ? (botY - topY) / 2 : (botY - topY);
  let shape = typeof viz.shape === "string" ? viz.shape : "sine";
  if (viz.shape && viz.shape.key) {
    const i = parseInt(ctx.getParam(viz.shape.key) || "0", 10);
    shape = viz.shape.shapes[isNaN(i) ? 0 : i] || "sine";
  }
  let phase = 0;
  if (viz.phaseKey) {
    const pv = parseInt(ctx.getParam(viz.phaseKey) || "0", 10);
    phase = isNaN(pv) ? 0 : pv / KIT_PARAM_MAX;
  }
  for (let x = x0; x <= x0 + spanW; x += 2) ctx.setPixel(x, baseY, 1);
  const yAt = (i) => {
    const v = shapeSample(shape, (i / spanW) * 2 + phase);
    return bipolar ? Math.round(baseY - v * amp) : Math.round(botY - ((v + 1) / 2) * amp);
  };
  let px = x0, py = yAt(0);
  for (let i = 1; i <= spanW; i++) {
    const y = yAt(i);
    plotLine(ctx, px, py, x0 + i, y, 1);
    px = x0 + i; py = y;
  }
  if (viz.retrigKey && parseInt(ctx.getParam(viz.retrigKey) || "0", 10) > 0) {
    ctx.fillRect(x0, Math.max(topY, Math.min(botY - 2, yAt(0) - 1)), 3, 3, 1);
  }
}

/* Vertical bipolar step bar: full-width center baseline, fill growing UP
 * for + and DOWN for - (classic step-sequencer level display). */
function drawVStep(ctx, x, w, top, h, signed, fg) {
  const cyc = top + Math.floor(h / 2);
  ctx.fillRect(x, cyc, w, 1, fg);
  const half = Math.floor(h / 2);
  const mag = Math.round(half * Math.min(1, Math.abs(signed)));
  if (signed >= 0) { if (mag > 0) ctx.fillRect(x, cyc - mag, w, mag, fg); }
  else if (mag > 0) ctx.fillRect(x, cyc + 1, w, mag, fg);
}

/* Step-sequencer editor (the sub-page reached by jogging RIGHT from a bank
 * with `steps`; jog LEFT backs out) — echidna's design: the 8 knobs are a
 * row of step faders for the current page of 8 steps, playhead = the active
 * step's number underlined, steps past the count inactive (dashed). */
function drawStepEditor(ctx, bank, s) {
  const vals = stepVals(ctx, bank);
  const center = stepsCenter(bank);
  const count = stepCount(ctx, bank);
  const page = (s.sub || 1) - 1;
  const pageCount = Math.max(1, Math.ceil(count / 8));
  drawChrome(ctx, bank.label + " STEPS " + (page + 1) + "/" + pageCount, s);
  // touched step's signed value, right-aligned in the inverted header
  if (s.lastKnob >= 0 && page * 8 + s.lastKnob < count) {
    const gidx = page * 8 + s.lastKnob;
    const sv = vals[gidx] - center;
    const rd = "S" + (gidx + 1) + " " + (sv > 0 ? "+" : "") + sv;
    hdrPrint(ctx, ctx.width - 2 - hdrWidth(rd), 1, rd, 1);
  }
  const playhead = stepPlayhead(ctx, bank, count);
  const dY = HDR_H + 5, dBot = ctx.height - 2, dH = dBot - dY; // frame top clears the indicator bar
  const colW = Math.floor(ctx.width / 8);
  for (let k = 0; k < 8; k++) {
    const stepIdx = page * 8 + k;
    const x = k * colW;
    const active = stepIdx < count;
    const touched = k === s.lastKnob && active;
    if (!active) {
      const cyc = dY + Math.floor(dH / 2);
      for (let dx = 1; dx < colW - 2; dx += 2) ctx.setPixel(x + dx, cyc, 1);
      continue;
    }
    const numStr = String(stepIdx + 1);
    const nw = ctx.measureText(numStr);
    if (touched) ctx.fillRect(x + 1, dY - 1, nw + 2, 8, 1);
    const nfg = touched ? 0 : 1;
    ctx.print(x + 2, dY, numStr, nfg);
    if (stepIdx === playhead) ctx.fillRect(x + 2, dY + 6, nw, 1, nfg);
    const barTop = dY + 9, barH = dH - 9;
    drawVStep(ctx, x + 2, colW - 5, barTop, barH, (vals[stepIdx] - center) / center, 1);
  }
  // frame + column dividers, matching the param grid's lined look
  const fTop = dY - 2;
  ctx.drawRect(0, fTop, ctx.width, dBot - fTop + 1, 1);
  for (let c = 1; c < 8; c++) ctx.fillRect(c * colW - 1, fTop, 1, dBot - fTop + 1, 1);
}

/* Framed HUD popup card (for CONFIG.overlays value-HUDs — the wave/tune2
 * card pattern): clears + frames a centered card, prints title left +
 * value right, and returns the body rect for the overlay to fill. */
function hudCard(ctx, title, valueText) {
  const x = 6, y = 11, w = ctx.width - 12, h = 42;
  ctx.fillRect(x, y, w, h, 0);
  ctx.drawRect(x, y, w, h, 1);
  ctx.print(x + 3, y + 2, fitText(ctx, title, w - 40), 1);
  if (valueText != null) {
    const vtxt = String(valueText);
    ctx.print(x + w - 3 - ctx.measureText(vtxt), y + 2, vtxt, 1);
  }
  ctx.fillRect(x + 1, y + 9, w - 2, 1, 1);
  return { x: x + 2, y: y + 11, w: w - 4, h: h - 13 };
}

/* Scrolling option-list overlay while a >2-option enum cell is touched.
 * Centred in the shared ZOOM box (v29, from davebox) rather than the old
 * side panel: it reads as one control wherever the touched knob is, and it
 * shares its footprint with the turn-to-reveal value zoom so the two don't
 * look like two different pop-ups. Header font, selection inverted, scrollbar
 * only when the options overflow. Toggles skip it (the hbar says it all). */
function drawEnumOverlay(ctx, cells, s) {
  const k = s.lastKnob;
  const cell = k >= 0 ? cells[k] : null;
  // Any cell carrying a discrete option list gets the picker — a named enum,
  // a length, a direction and a modulation target are the same thing to the
  // user: a limited set to browse. (davebox keys off options, not kind.)
  if (!cell || !cell.options || cell.options.length <= 2) return;
  const sel = getRaw(ctx, cell) - cell.min;
  if (sel < 0) return;   // unset value — nothing to browse

  const X = ZOOM_X, Y = ZOOM_Y, W = ZOOM_W, H = ZOOM_H;
  ctx.fillRect(X, Y, W, H, 0);
  ctx.drawRect(X, Y, W, H, 1);

  const n = cell.options.length;
  const ROW_H = 9;                                   // header-font line
  const VISIBLE = Math.max(1, Math.min(n, Math.floor((H - 4) / ROW_H)));
  const hasScroll = n > VISIBLE;
  const half = Math.floor(VISIBLE / 2);
  const start = Math.max(0, Math.min(sel - half, n - VISIBLE));
  const listTop = Y + Math.floor((H - VISIBLE * ROW_H) / 2);
  const rowX = X + 2, rowW = W - 4 - (hasScroll ? 4 : 0);
  const availW = rowW - 4;
  for (let i = 0; i < VISIBLE; i++) {
    const idx = start + i;
    if (idx >= n) break;
    const y = listTop + i * ROW_H;
    let label = String(cell.options[idx]);
    while (label.length > 1 && hdrWidth(label) > availW) label = label.slice(0, -1);
    if (idx === sel) {
      ctx.fillRect(rowX, y, rowW, ROW_H, 1);
      hdrPrint(ctx, rowX + 3, y + 1, label, 0);
    } else {
      hdrPrint(ctx, rowX + 3, y + 1, label, 1);
    }
  }
  /* Scroll indicator: right-edge track + thumb, only when there's overflow. */
  if (hasScroll) {
    const trackH = VISIBLE * ROW_H;
    const thumbH = Math.max(3, Math.round(trackH * VISIBLE / n));
    const thumbY = listTop + Math.round((trackH - thumbH) * start / Math.max(1, n - VISIBLE));
    ctx.fillRect(X + W - 2, listTop, 1, trackH, 1);
    ctx.fillRect(X + W - 3, thumbY, 2, thumbH, 1);
  }
}

/* The per-bank frame: header + two widget/label rows; env banks swap row 0's
 * widgets for the full-width envelope graphic. */
function drawBankView(ctx, bank, cells, s) {
  const hdr = headerTextFor(ctx, bank, s, cells);
  drawChrome(ctx, hdr.text, s, hdr.centered);
  if (bank.env) {
    const e = envSpec(bank.env);
    drawEnvelopeRow(ctx, ROW0_Y, cells, bank.env);
    for (let col = 0; col < 4; col++) {
      if (!cells[col]) continue;
      // Cells the graphic doesn't cover keep their knob widget (partial envs).
      const inEnv = col >= e.startCol && col < e.startCol + e.cellCount;
      if (!inEnv) drawWidget(ctx, col, ROW0_Y, cells[col], col === s.lastKnob);
      drawLabelCell(ctx, col, LBL0_Y, cells[col], col === s.lastKnob);
    }
    for (let col = 0; col < 4; col++) {
      const cell = cells[4 + col];
      if (!cell) continue;
      drawWidget(ctx, col, ROW1_Y, cell);
      drawLabelCell(ctx, col, LBL1_Y, cell, (4 + col) === s.lastKnob);
    }
  } else {
    const viz = bank.lfoViz;
    const fviz = bank.filterViz;
    for (let k = 0; k < 8; k++) {
      const cell = cells[k];
      if (!cell) continue;
      const col = k % 4, rowY = k < 4 ? ROW0_Y : ROW1_Y, lblY = k < 4 ? LBL0_Y : LBL1_Y;
      const inViz = viz && (k === viz.cell || k === viz.cell + 1);
      const inFlt = fviz && (k === fviz.cell || k === fviz.cell + 1);
      if (!inViz && !inFlt) drawWidget(ctx, col, rowY, cell, k === s.lastKnob);
      drawLabelCell(ctx, col, lblY, cell, k === s.lastKnob);
    }
    if (viz) drawLfoWave(ctx, viz, cells);
    if (fviz) drawFilterCurve(ctx, fviz);
  }
  drawEnumOverlay(ctx, cells, s);
  // Module hooks: transient value-HUDs etc. Each fn(ctx, cells, s) draws on
  // top of the bank view (use hudCard for the standard popup frame).
  if (CONFIG.overlays) for (const fn of CONFIG.overlays) fn(ctx, cells, s);
}

/* ---- the overlay object ---- */

const bank_editor = {
  onOpen(ctx) {
    ctx.state.init = false; // force re-seed from the persisted value
    readState(ctx);
  },

  onMidi(ctx, payload) {
    const d = payload && payload.data;
    if (!d || d.length < 3) return;
    const s = readState(ctx);
    const status = d[0] & 0xF0;

    if (status === 0x90 || status === 0x80) { // capacitive touch: notes 0-7 knobs
      const note = d[1];
      if (note <= 7) s.lastKnob = (status === 0x90 && d[2] >= 64) ? note : -1;
      return;
    }
    if (status !== 0xB0) return;
    const cc = d[1], val = d[2];

    // CC-49 fallback for off-device runs; on device shift arrives via the
    // shadow_get_shift_held() SHM poll (the shim doesn't forward CC 49 here).
    if (cc === 49) { s.shift = val >= 64; s.jogAccum = 0; return; }

    if (cc === 14) { // jog turn: steps banks either way; SHIFT adds the overlay
      const jd = dirFromCC(val);
      if (jd) {
        if (shiftHeld(s)) {
          // Shift+jog: step the picker section-to-section (NAV_SENS detents
          // per step), landing on that section's first bank. Plain jog stays
          // 1:1 through every bank with no overlay.
          const nr = accumStep(s.jogAccum, jd, NAV_SENS);
          s.jogAccum = nr.accum;
          if (!nr.fire) return;
          const ni = clampBank(activeSection(s.bank) + jd, JUMP_SECTIONS.length);
          s.bank = JUMP_SECTIONS[ni].bank;
          s.sub = 0;
        } else {
          s.jogAccum = 0;
          // Step-editor sub-pages first (jog RIGHT into / deeper, jog LEFT
          // back out), then spill over to the next/previous bank.
          const subMax = subPageCount(ctx, BANKS[s.bank]);
          const sub = s.sub || 0;
          if (jd > 0 && sub < subMax) {
            s.sub = sub + 1;
          } else if (jd < 0 && sub > 0) {
            s.sub = sub - 1;
          } else {
            s.bank = clampBank(s.bank + jd, BANKS.length);
            s.sub = 0;
          }
        }
        ctx.setValue(String(s.bank));  // persist for re-open
        s.lastKnob = -1;
        s.stepSelKey = null;           // re-seed the step cursor on next edit
      }
      return;
    }

    if (cc < 71 || cc > 78) return;
    const k = cc - 71;
    const dir = dirFromCC(val);
    if (!dir) return;
    const bank = BANKS[s.bank];
    const cell = cellsFor(ctx, bank, s.sub || 0, s)[k];
    if (!cell || cell.kind === "blank") return;   // empty slot on this bank

    if (cell.kind === "steplvl") {
      // Step editor: set the engine's step cursor only when the target step
      // CHANGES, track the value in state so a sustained turn is ONE
      // blocking write per fire (echidna's sel/lvl protocol).
      if (cell.stepIdx >= stepCount(ctx, bank)) return; // inactive step
      s.lastKnob = k;
      const sr = accumStep(s.accum[k], dir, KIT_SENS);
      s.accum[k] = sr.accum;
      if (!sr.fire) return;
      const selKey = s.bank + ":" + cell.stepIdx;
      if (s.stepSelKey !== selKey) {
        ctx.setParam(bank.steps.sel, String(cell.stepIdx));
        s.stepSelKey = selKey;
        s.stepVal = stepVals(ctx, bank)[cell.stepIdx];
      }
      let sv = s.stepVal + dir;
      if (sv < 0) sv = 0;
      if (sv > stepsMax(bank)) sv = stepsMax(bank);
      if (sv !== s.stepVal) { ctx.setParam(bank.steps.lvl, String(sv)); s.stepVal = sv; }
      return;
    }
    s.lastKnob = k;

    // All kinds (incl. enum) step-and-CLAMP; accumulate cell.sens detents
    // per step (knob feel + fewer blocking writes).
    const cr = accumStep(s.accum[k], dir, cell.sens || 2);
    s.accum[k] = cr.accum;
    if (!cr.fire) return;
    // Read + step in the native-int domain (getRaw applies get/parse hooks);
    // write via cell.set (local cells) or the wire format (cell.format).
    const cur = getRaw(ctx, cell);
    let nv = cur + dir * cell.step;
    if (nv < cell.min) nv = cell.min;
    if (nv > cell.max) nv = cell.max;
    if (nv === cur) return;
    if (cell.set) cell.set(ctx, nv);
    else ctx.setParam(cell.key, cell.format ? String(cell.format(nv)) : String(nv));
  },

  draw(ctx) {
    // One-time per-ctx install (guarded; draw runs every frame).
    if (!ctx._pfInstalled) {
      // (1) Text via the 5x5 pixel-font (the host's native OLED font has
      // different glyphs/metrics). Override print + measureText -> the layout
      // code routes every string through these.
      ctx.print = function (x, y, text, color) { pfPrint(ctx, x, y, text, color ? 1 : 0); };
      ctx.measureText = function (str) { return pfWidth(str); };
      // (2) getParam cache. On device each ctx.getParam is a ~2.6ms blocking
      // SHM round-trip, and the layout reads one per cell EVERY frame. Cache
      // reads; write-through on setParam so knob turns reflect instantly; and
      // full-refresh a couple times/sec to catch external changes (preset load).
      var rawGet = ctx.getParam, rawSet = ctx.setParam;
      ctx._pcache = {};
      ctx.getParam = function (k) {
        if (Object.prototype.hasOwnProperty.call(ctx._pcache, k)) return ctx._pcache[k];
        var v = rawGet.call(ctx, k);
        ctx._pcache[k] = v;
        return v;
      };
      var stepKeys = {};
      for (var bi = 0; bi < BANKS.length; bi++) {
        if (BANKS[bi].steps) { stepKeys[BANKS[bi].steps.sel] = BANKS[bi].steps.csv; stepKeys[BANKS[bi].steps.lvl] = BANKS[bi].steps.csv; }
      }
      ctx.setParam = function (k, v) {
        var r = rawSet.call(ctx, k, v);
        ctx._pcache[k] = String(v);   // reflect the write now
        if (stepKeys[k]) delete ctx._pcache[stepKeys[k]];  // sel/lvl writes dirty the CSV mirror
        // CONFIG.writeInvalidates(key) -> true = flush everything (preset
        // load), array = drop those keys (include key itself when the engine
        // may not land on the written value — select skip-walks), else null.
        // Caching a value the engine rewrote is the classic desync bug.
        if (CONFIG.writeInvalidates) {
          var inv = CONFIG.writeInvalidates(k);
          if (inv === true) ctx._pcache = {};
          else if (inv) for (var ii = 0; ii < inv.length; ii++) delete ctx._pcache[inv[ii]];
        }
        return r;
      };
      ctx._cacheTick = 0;
      ctx._pfInstalled = true;
    }
    // Periodic full refresh (~2x/sec) so external param changes surface.
    if ((ctx._cacheTick = (ctx._cacheTick + 1) % 24) === 0) ctx._pcache = {};

    const s = readState(ctx);
    const bank = BANKS[s.bank];
    if (bank.steps && (s.sub || 0) >= 1) drawStepEditor(ctx, bank, s);
    else drawBankView(ctx, bank, cellsFor(ctx, bank, 0, s), s);
    drawBankPicker(ctx, s);
  },

  _test: Object.assign({
    BANKS, JUMP_SECTIONS, activeSection, NAV_SENS, shiftHeld,
    dirFromCC, clampBank, accumStep,
    formatCell, DEFAULTS, kToggleLabels,
    drawBankIcon, BANK_ICONS, ICON_W, iconW,
    widgetFor, enumSquareLines, pf3Width, CONFIG, envSpec, filtGainAt,
    cellsFor, headerFor, headerTextFor, getRaw, subPageCount, stepCells, stepVals, shapeSample, hudCard
  }, CONFIG.testExports || {})
};


globalThis.bank_editor = bank_editor;
})();
